<aside class="span4 right-sidebar">
                    
                    <!--  ==========  -->
                    <!--  = Search Widget =  -->
                    <!--  ==========  -->
                    <div class="sidebar-item widget_search">
                        <!-- <div class="underlined">
                            <h3><span class="light">Search</span></h3>
                        </div> -->
                        
                        <form class="form" action="#" id="searchform" method="get" role="search">
                            <input type="text" id="appendedInputButton" class="input-block-level" name="s" placeholder="Search for posts ...">
                            <button type="submit">
                                <i class="icon-search"></i>
                            </button>
                        </form>
                    </div>
                    
                    <!--  ==========  -->
                    <!--  = Flickr Widget =  -->
                    <!--  ==========  -->
                    <div class="sidebar-item widget_flickr">
                        <div class="underlined">
                            <h3><span class="light">Flickr</span> Widget</h3>
                        </div>
                        
                        <div class="flickr-badge clearfix">
                            <!-- Start of Flickr Badge -->
                            <div id="flickr_badge_uber_wrapper">
                                <div id="flickr_badge_wrapper">
                                    <script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?count=9&amp;display=latest&amp;size=s&amp;layout=x&amp;source=group&amp;group=80641914@N00"></script>
                                </div>
                            </div>
                            <!-- End of Flickr Badge -->
                        </div>
                    </div>
                    
                  
                    
                    <!--  ==========  -->
                    <!--  = Twitter Widget =  -->
                    <!--  ==========  -->
                    <div class="sidebar-item widget_twitter">
                        <div class="underlined">
                            <h3><span class="light">Twitter</span> Feed</h3>
                        </div>
                        
                        <a class="twitter-timeline" href="https://twitter.com/GankGamingTV" data-widget-id="GankGamingTV">Tweets by @primozcigler</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

                    </div>
                    
                    
                </aside>