<?php echo $this->render('layout/bread.phtml')?>
        
        <div class="workplace">
			<div class="page-header">
                    <h1>Quản lý <small>thông số</small></h1>
            </div>
            <?php echo $this->render('layout/menusanpham.phtml')?>
            
            <div class="row-fluid">
                <?php
				$form = $this->form;
				$form->setAttributes ( array (
				'id' => 'validation' ) );
				$form->setAttribute ( 'action', $this->url ( 'thongso', array (
				'action' => 'list' ) ) );
				$form->prepare ();
				echo $this->form ()->openTag ( $form );
				?>
                <div class="span12">   
                <?php echo $this->formhidden($form->get('id'))?>               
                    <div class="head">
                        <div class="isw-list"></div>
                        <h1>Thông số</h1>
						<ul class="buttons">
                                <li><a href="#" class="isw-ok"></a></li>
                                
                            </ul>
                        <div class="clear"></div>
                    </div>
                    <div class="block-fluid">
						<div class="row-form">
										<div class="span2">Tên thông số :</div>
										<div class="span3"><?php echo $this->forminput($form->get('name'))?></div>
										<div class="span2 offset1">Đơn vị :</div>
										<div class="span3">
											<?php echo $this->forminput($form->get('units'))?></div>
										<div class="clear"></div>
							</div>
							<div class="row-form">
										<div class="span2">Mô tả :</div>
										<div class="span3"><?php echo $this->formtextarea($form->get('description'))?></div>
										<div class="span2 offset1">Danh mục :</div>
										<div class="span3">
											<?php echo $this->formselect($form->get('category'))?>
										</div>
										<div class="clear"></div>
							</div>
							<div class="row-form">
										<div class="span2">Thuộc thông số :</div>
										<div class="span3"><?php echo $this->formselect($form->get('parents'))?></div>
										<div class="span2 offset1">Kích hoạt :</div>
										<div class="span3">
											<?php echo $this->formselect($form->get('active'))?>
										</div>
										<div class="clear"></div>
							</div>
							
							<div class="footer tar">
                                <button class="btn"> Thêm thông số </button>
							</div>	
                    </div>
                </div>                                
                </form>
            </div> 
            <div class="row-fluid">
                
                <div class="span12">                    
                    <div class="head">
                        <div class="isw-grid"></div>
                        <h1>Danh sách</h1>
						<ul class="buttons">
                            <li><a href="#" class="isw-download"></a></li>                                                        
                            <li><a href="#" class="isw-attachment"></a></li>
                            <li>
                                <a href="#" class="isw-settings"></a>
                                <ul class="dd-list">
                                    <li><a href="#"><span class="isw-plus"></span> New document</a></li>
                                    <li><a href="#"><span class="isw-edit"></span> Edit</a></li>
                                    <li><a href="#"><span class="isw-delete"></span> Delete</a></li>
                                </ul>
                            </li>
                        </ul>               
                        <div class="clear"></div>
                    </div>
					
                    <div class="block-fluid table-sorting">
                        <table cellpadding="0" cellspacing="0" width="100%" class="table" id="tSortable">
                            <thead>
                                <tr>
                                    <th width="5%"><input type="checkbox" name="checkall"/></th>
                                    <th width="5%">STT</th>
									<th width="15%">Tên thông số</th>
									<th width="10%">Đơn vị</th>
									<th width="20%">Mô tả</th>
                                    <th width="15%">Danh mục</th>
									<th width="10%">Thuộc thông số</th>
                                    <th width="10%">Trạng thái</th>
									<th width="10%">Hành động</th>                                    
                                </tr>
                            </thead>
                            <tbody class="category">
                            <?php foreach ($thongso as $thongsos):?>
                                <tr>
                                    <td><input type="checkbox" name="checkbox"/></td>
                                    <td><?php echo $thongsos->id?></td>
                                    <td><?php echo $thongsos->name ?></td>
                                    <td><?php echo $thongsos->units ?></td>
                                    <td><?php echo $thongsos->description ?></td>
									<td><?php if($thongsos->parents != 0) {echo $cate[$parent1[$thongsos->parents]['category']];} else {echo $cate[$thongsos->category] ;} ?></td>
                                    <td><?php echo $parent[$thongsos->parents] ?></td>
                                    <td><?php if($thongsos->active = 1) echo "Được kích hoạt"; else echo "Tạm ngưng" ?></td>
                                    <td class="action_hanhdong">
										<a href="javascript::void()" title="Sửa" data-href="<?php echo $this->url('thongso',array('action'=>'edit','id'=>$thongsos->id))?>" id="dialogBtn"><i class="fa fa-pencil-square-o"></i></a>
										<a data-href="<?php echo $this->url('thongso', array('action'=>'delete','id'=>$thongsos->id))?>" href="javascript::void()" class="delete"><i class="fa fa-trash-o" title="Xóa"></i></a>
									</td>
                                    
                                </tr>
                             <?php endforeach;?>
                                       
                            </tbody>
                        </table>
                        <div class="clear"></div>
                    </div>
                </div>                                
                
            </div>            
            
            <div class="dr"><span></span></div>            
            
        </div>
        <script type='text/javascript'>
		$(document).ready(function(){
			$("#dialog").dialog({
				autoOpen: false,
				modal: true,
				height: 600,
				width: 960,
				show: 'blind',
				
				 
			});

			
			$('body').on('click','a#dialogBtn', function(){
				var ahref = $(this).attr('data-href');
				$('#dialog').dialog('open');
				$('#myIframe').attr('src', ahref);
				
			})
			
			$('body').on('click','a.delete', function()
			{
				var r = confirm("Nếu xóa thì các liên kết đến thông số sẽ được xóa bỏ. Bạn có chắc chắn xóa thông tin này");
				if (r == true) {
					var URL = $(this).attr("data-href");
					
					$.ajax({
						type: "POST",
						url: URL,
						cache: false,
						success: function(html){
							
							notify_s('Thông báo','Bạn đã xóa thành công');
							
						}
					})
					$(this).closest("tbody.category tr").fadeOut(function(){$(this).remove()});
				} 
				
			});
		})
	</script>
	<div id="dialog">
			<iframe id="myIframe" src="" width="100%" height="100%" style="border: 1px solid #ccc"></iframe>
	</div>
        	<script type="text/javascript">
			function closeModal() {
			    $("#dialog").dialog("close");
			}
			</script>