<?php echo $this->render('layout/bread.phtml')?>
        
        <div class="workplace">
			<div class="page-header">
                    <h1>Quản lý <small>block</small></h1>
            </div>
           
            <?php echo $this->render('layout/menublock.phtml')?>
            <div class="row-fluid">
                <?php
				$form = $this->form;
				$form->setAttributes ( array (
				'id' => 'validation' ) );
				$form->setAttribute ( 'action', $this->url ( 'slide', array (
				'action' => 'list' ) ) );
				$form->prepare ();
				echo $this->form ()->openTag ( $form );
				
				?>
				
                <div class="span12">   
                       <?php 
                       echo $this->formhidden($form->get('module')->setValue(4));
                       echo $this->formhidden($form->get('html'));
                       echo $this->formhidden($form->get('css'));
                       echo $this->formhidden($form->get('link'));
                       echo $this->formhidden($form->get('id'));
                       ?>   
                    <div class="head">
                        <div class="isw-list"></div>
                        <h1>Slide</h1>
						<ul class="buttons">
                                <li><a href="#" class="isw-ok"></a></li>
                                
                            </ul>
                        <div class="clear"></div>
                    </div>
                    <div class="block-fluid">
						<div class="row-form">
										<div class="span2">Tên slide :</div>
										<div class="span3"><?php echo $this->forminput($form->get('name'))?></div>
										<div class="span2 offset1">Chọn vị trí hiển thị :</div>
										<div class="span3">
											<?php echo $this->formselect($form->get('position'))?>

										</div>
										<div class="clear"></div>
							</div>
							<div class="row-form">
										<div class="span2">Trang hiển thị :</div>
										<div class="span3">
											<ul style="list-style:none; margin: 0">
			                                   	<?php foreach ($page as $pages):?>
			                                   		<li><input type="checkbox" name="page[]" class="page" value="<?php echo $pages['id']?>"/>
			                                   		 <?php echo $pages['name']?>  </li>
			                                   	<?php endforeach;?>
		                                   	</ul>
										</div>
										<div class="span2 offset1">Kích hoạt :</div>
										<div class="span3">
											<?php echo $this->formselect($form->get('active'))?>
										</div>
										<div class="clear"></div>
							</div>
							
							<div class="footer tar">
                                <button class="btn"> Thêm slide </button>
							</div>	
                    </div>
                </div>                                
                </form>
            </div> 
            <div class="row-fluid">
                
                <div class="span12">                    
                    <div class="head">
                        <div class="isw-grid"></div>
                        <h1>Danh sách</h1>
						<ul class="buttons">
                            <li><a href="#" class="isw-download"></a></li>                                                        
                            <li><a href="#" class="isw-attachment"></a></li>
                            <li>
                                <a href="#" class="isw-settings"></a>
                                <ul class="dd-list">
                                    <li><a href="#"><span class="isw-plus"></span> New document</a></li>
                                    <li><a href="#"><span class="isw-edit"></span> Edit</a></li>
                                    <li><a href="#"><span class="isw-delete"></span> Delete</a></li>
                                </ul>
                            </li>
                        </ul>               
                        <div class="clear"></div>
                    </div>
                    <div class="block-fluid table-sorting">
                        <table cellpadding="0" cellspacing="0" width="100%" class="table" id="tSortable">
                            <thead>
                                <tr>
                                    <th width="5%"><input type="checkbox" name="checkall"/></th>
                                    <th width="5%">STT</th>
									<th width="10%">Tên block</th>
                                    <th width="10%">Vị trí</th>
									<th width="15%">Example</th>
                                    <th width="10%">Tình trạng</th>
									<th width="15%">Hiển thị tại các trang</th>
                                    <th width="20%">Giá trị</th>
									<th width="10%">Hành động</th>                                    
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($Slide as $Blocks):?>
                                <tr class="edit_<?php echo $Blocks->id ?>">
                                    <td><input type="checkbox" name="checkbox"/></td>
                                    <td><?php echo $Blocks->id ?></td>
                                    <td><?php echo $Blocks->name ?></td>
                                    <td><select name="position" class="position" style="width: 100%">
                                    <?php foreach ($position as $positions):?>
                                    	<option value="<?php echo $positions['alias']?>" <?php if($Blocks->position == $positions['alias']) echo "selected"; ?>>
                                    		<?php echo $positions['alias']?>
                                    	</option>
                                    <?php endforeach;?>
                                    </select></td>
                                    <td>
                                    
                                    </td>
									<td>
									<select class="active" style="width: 100%" disabled>
                                    <option value="0" <?php if($Blocks->active == 0 ) echo "selected"?>>Ngưng</option>
                                    <option value="1" <?php if($Blocks->active == 1 ) echo "selected"?>>Hoạt động</option>
                                    </select>
									
                                    <td>
	                                   	<ul style="list-style:none; margin: 0">
	                                   	<?php foreach ($page as $pages):?>
	                                   		<li><input type="checkbox" name="page[]" class="page" value="<?php echo $pages['id']?>" 
	                                   		<?php foreach ($pageSlide as $pageblocks) { if($Blocks->id == $pageblocks['idblock'] && $pages['id'] == $pageblocks['idpage']) { echo "checked"; } }?>
	                                   		/>
	                                   		 <?php echo $pages['name']?>  </li>
	                                   	<?php endforeach;?>
	                                   	</ul>
                                    </td>
                                    <td>
                                    <a href="<?php echo $this->url('slide', array('action'=>'image', 'id'=>$Blocks->id))?>">Click vào để thêm hình ảnh</a>
                                    </td>
                                    <td class="action_hanhdong">
										<a href="javascript::void()" title="Sửa" id="edit" edit-id="<?php echo $Blocks->id?>" ><i class="fa fa-pencil-square-o"></i></a>
									
									</td>
                                </tr>
                            <?php endforeach;?>                                
                            </tbody>
                        </table>
                        <div class="clear"></div>
                    </div>
                </div>                                
                
            </div>            
            
            <div class="dr"><span></span></div>            
            
        </div>
	<script type="text/javascript">

	$(document).ready(function(){
		$('body').on('click','.action_hanhdong #edit', function(){
			var edit_id = $(this).attr('edit-id');
			
			if($(this).children('i').attr('class') == 'fa fa-pencil-square-o')
			{
				$(this).children('i').attr('class','fa fa-floppy-o');
				$('tr.edit_'+edit_id+ ' input').prop('disabled', false);
				$('tr.edit_'+edit_id+ ' select').prop('disabled', false);
			} else {
				$(this).children('i').attr('class','fa fa-pencil-square-o');
				$('tr.edit_'+edit_id+ ' input').prop('disabled', true);
				$('tr.edit_'+edit_id+ ' select').prop('disabled', true);
				var url = "<?php echo $this->url('block', array('action'=>'edit'))?>" + '/' + edit_id;
				var position = $('tr.edit_'+edit_id+ ' select.position').val();
				var page = $('tr.edit_'+edit_id+ ' input:checkbox:checked.page'),
			    names  = [].map.call(page, function( input ) {
			        return input.value;
			    });
				var active = $('tr.edit_'+edit_id+ ' select.active').val();

				var valueblock1 = $('tr.edit_'+edit_id+ ' input.value1'),
			    blockvalue1  = [].map.call(valueblock1, function( input ) {
			        return input.value;
			    });
			    var idblockcontent1 = $('tr.edit_'+edit_id+ ' input.idblockcontent1').val();

				var valueblock2 = $('tr.edit_'+edit_id+ ' input.value2'),
			    blockvalue2  = [].map.call(valueblock2, function( input ) {
			        return input.value;
			    });
				var idblockcontent2 = $('tr.edit_'+edit_id+ ' input.idblockcontent2').val();
				
				var dataString = 'position=' + position +'&page='+ names +'&active='+ active +'&blockvalue1='+ blockvalue1 +'&blockvalue2='+ blockvalue2 +'&idblockcontent1='+ idblockcontent1 +'&idblockcontent2='+ idblockcontent2;
				
				$.ajax({
					type: "POST",
					url: url,
					data: dataString,
					cache: false,
					success: function(html){
						
						notify_s('Thông báo','Bạn đã cập nhập thành công');
						
					}
				})
				
			}
		})
	})
	</script>