 <div class="breadLine">
       
            <ul class="breadcrumb">
            <li><a href="<?php echo $this->url('application', array('action'=>'index'))?>">Trang chủ</a> <span class="divider">&gt;</span></li>
                <?php
			     // iterate through the pages
			     foreach ($this->pages as $key => $page):
			         ?>
			         <li>
			             <?php
			             // if this isn't the last page, add a link and the separator
			             if ($key < count($this->pages) - 1):
			                 ?>
			                 <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
			                 <span class="divider">&gt;</span>
			             <?php
			             // otherwise, just output the name
			             else:
			             ?>
			                 <?php echo $page->getLabel(); ?>
			             <?php endif; ?>
			         </li>
			    <?php endforeach; ?>
            </ul>
                        
            <ul class="buttons">
                <li>
                    <a href="#" class="link_bcPopupList"><span class="icon-user"></span><span class="text">Users list</span></a>

                           
                    
                </li>                
                <li>
                    <a href="#" class="link_bcPopupSearch"><span class="icon-search"></span><span class="text">Search</span></a>
                    
                    <div id="bcPopupSearch" class="popup">
                        <div class="head">
                            <div class="arrow"></div>
                            <span class="isw-zoom"></span>
                            <span class="name">Search</span>
                            <div class="clear"></div>
                        </div>
                        <div class="body search">
                            <input type="text" placeholder="Some text for search..." name="search"/>
                        </div>
                        <div class="footer">
                            <button class="btn" type="button">Search</button>
                            <button class="btn btn-danger link_bcPopupSearch" type="button">Close</button>
                        </div>
                    </div>                
                </li>
            </ul>
            
        </div>