
<script type="text/javascript">
function BrowseServer( startupPath, functionData )
{
	// You can use the "CKFinder" class to render CKFinder in a page:
	var finder = new CKFinder();

	// The path for the installation of CKFinder (default = "/ckfinder/").
	finder.basePath = '../';

	//Startup path in a form: "Type:/path/to/directory/"
	finder.startupPath = startupPath;

	// Name of a function which is called when a file is selected in CKFinder.
	finder.selectActionFunction = SetFileField1;

	// Additional data to be passed to the selectActionFunction in a second argument.
	// We'll use this feature to pass the Id of a field that will be updated.
	finder.selectActionData = functionData;

	// Name of a function which is called when a thumbnail is selected in CKFinder.
	finder.selectActionFunction = ShowThumbnails1;

	// Launch CKFinder
	finder.popup();
}

// This is a sample function which is called when a file is selected in CKFinder.
function SetFileField1( fileUrl, data )
{
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

// This is a sample function which is called when a thumbnail is selected in CKFinder.
function ShowThumbnails1( fileUrl, data )
{

	// this = CKFinderAPI
	var sFileName = this.getSelectedFile().name;
	document.getElementById('uploader_v5_filelist').innerHTML +=
		'<li><div class="widgetButtons">' +                        
        '<div class="bb" id="boanh1">' +
            '<a href="#" class="tipb" title="" data-original-title="Edit item" style="padding: 0">' +
			'<div class="imgItem lm10 rm10" style=" position: relative; width: 110px; height: 110px;' + 
			'background-image: url(' + "'" + fileUrl + "'" + '); background-size: cover; background-position: initial initial;' + 
			'background-repeat: no-repeat no-repeat;">' +
			'<div class="op trans" style="position: absolute; top: -10px; right: -10px; width: 25px; height: 25px;' + 
			'cursor: pointer; border-radius: 25px;"></div></div>' +
			'</a>' +
			'<input type="hidden" name="imageshow[]" value="' + fileUrl + '" />'+
            '<div class="caption red"><i class="icon-remove"></i></div>' +
        '</div>' +
        
		'</div></li>';

	// It is not required to return any value.
	// When false is returned, CKFinder will not close automatically.
	
	return true;
}
$(document).on("click", ".icon-remove", function(){
	$(this).closest(".plupload_filelist li").fadeOut(function(){$(this).remove();});
	
});

</script>
<?php echo $this->render('layout/bread.phtml')?>
        
        <div class="workplace">
			<div class="page-header">
                    <h1>Bộ ảnh <small><?php echo $album->name ?></small></h1>
            </div>
            
     		<div class="row-fluid">
               <?php
				$form = $this->form;
				$form->setAttributes ( array (
				'id' => 'validation' ) );
				$form->setAttribute ( 'action', $this->url ( 'albumanh', array (
				'action' => 'item','id'=>$this->id ) ) );
				$form->prepare ();
				echo $this->form ()->openTag ( $form );
				?>
				
                <div class="span12">  
                <input type="hidden" name="id" />                  
                    <div class="head">
                        <div class="isw-list"></div>
                        <h1>Album ảnh</h1>
						<ul class="buttons">
                                <li><a href="#" class="isw-ok"></a></li>
                                
                            </ul>
                        <div class="clear"></div>
                    </div>
                    <div class="block-fluid">
						<div class="row-form">
							<div class="span12">
								<h4 style="font-family: Cambria, Georgia, serif; font-style: italic">
									Bộ ảnh album</h4>
								<ul id="uploader_v5_filelist" class="plupload_filelist" style="height: 400px">
								<?php foreach ($Albumanh as $Albumanhs):?>
									<li>
										<div class="widgetButtons">
										<div class="bb" id="boanh1">
										<a href="#" class="tipb" title="" data-original-title="Edit item" style="padding: 0">
										<div class="imgItem lm10 rm10" style=" position: relative; width: 110px; height: 110px;
										background-image: url('<?php echo $Albumanhs['link'] ?>'); 
										background-size: cover; background-position: initial initial;
										background-repeat: no-repeat no-repeat;">
										<div class="op trans" style="position: absolute; top: -10px; right: -10px; width: 25px; height: 25px;cursor: pointer; border-radius: 25px;">
										</div></div>
										</a>
										<input type="hidden" name="imageshow[]" value="<?php echo $Albumanhs['link'] ?>">
										<div class="caption red"><i class="icon-remove"></i></div></div></div>
									</li>
								<?php endforeach;?>
								</ul>
								<div class="plupload_buttons">
									<a href="javascript::void()" class="plupload_button plupload_add" id="uploader_v5_browse" style="position: relative; z-index: 0;" onclick="BrowseServer( 'Images:/', 'xImagePath1' );"> Thêm
										hình ảnh </a>


								</div>

							</div>
							<div class="clear"></div>
						</div>
						<div class="footer tar">
						<button class="btn">Thêm ảnh</button>
						</div>	
                    </div>
                    
                </div>                                
                </form>
            </div>
            
            
            <div class="dr"><span></span></div>            
            
        </div>
        
    