
<script type="text/javascript">

function BrowseServer( startupPath, functionData )
{
	// You can use the "CKFinder" class to render CKFinder in a page:
	var finder = new CKFinder();

	// The path for the installation of CKFinder (default = "/ckfinder/").
	finder.basePath = '../';

	//Startup path in a form: "Type:/path/to/directory/"
	finder.startupPath = startupPath;

	// Name of a function which is called when a file is selected in CKFinder.
	finder.selectActionFunction = SetFileField;

	// Additional data to be passed to the selectActionFunction in a second argument.
	// We'll use this feature to pass the Id of a field that will be updated.
	finder.selectActionData = functionData;

	// Name of a function which is called when a thumbnail is selected in CKFinder.
	finder.selectActionFunction = ShowThumbnails;

	// Launch CKFinder
	finder.popup();
}

// This is a sample function which is called when a file is selected in CKFinder.
function SetFileField( fileUrl, data )
{
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

// This is a sample function which is called when a thumbnail is selected in CKFinder.
function ShowThumbnails( fileUrl, data )
{

	// this = CKFinderAPI
	var sFileName = this.getSelectedFile().name;
	document.getElementById('thumbnails').innerHTML = '';
	document.getElementById('thumbnails').innerHTML +=
			
			'<div class="thumb">' +
				'<img src="' + fileUrl + '" />' +
				'<div class="caption">' +
					'<a href="' + data["fileUrl"] + '" target="_blank">' + sFileName + '</a> (' + data["fileSize"] + 'KB)' +
				'</div>' +
			'</div>';

	
	// It is not required to return any value.
	// When false is returned, CKFinder will not close automatically.
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

</script>
<?php echo $this->render('layout/bread.phtml')?>
        
        <div class="workplace">
			<div class="page-header">
                    <h1>Quản lý <small>album ảnh</small></h1>
            </div>
            
     		<div class="row-fluid">
               <?php
				$form = $this->form;
				$form->setAttributes ( array (
				'id' => 'validation' ) );
				$form->setAttribute ( 'action', $this->url ( 'albumanh', array (
				'action' => 'list' ) ) );
				$form->prepare ();
				echo $this->form ()->openTag ( $form );
				?>
				
                <div class="span12">  
                <input type="hidden" name="id" />                  
                    <div class="head">
                        <div class="isw-list"></div>
                        <h1>Album ảnh</h1>
						<ul class="buttons">
                                <li><a href="#" class="isw-ok"></a></li>
                                
                            </ul>
                        <div class="clear"></div>
                    </div>
                    <div class="block-fluid">
						<div class="row-form">
										<div class="span2">Tên album :</div>
										<div class="span3"><?php echo $this->forminput($form->get('name'))?> <span> Tên đại diện album ảnh  </span></div>
										<div class="span2 offset1">Đường dẫn tối ưu :</div>
										<div class="span3">
											<?php echo $this->forminput($form->get('alias'))?>

										<span>Example : album-1 </span></div>
										<div class="clear"></div>
							</div>
							<div class="row-form">
										<div class="span2">Tag :</div>
										<div class="span3"><?php echo $this->forminput($form->get('tag'))?></div>
										<div class="span2 offset1">Tình trạng :</div>
										<div class="span3">
											<?php echo $this->formselect($form->get('active'))?>
										</div>
										
										<div class="clear"></div>
							</div>
							<div class="row-form">
										<div class="span2">Mô tả ngắn :</div>
										<div class="span3"><?php echo $this->formtextarea($form->get('summary'))?></div>
										<div class="span2 offset1">Hình ảnh :</div>
										<div class="span3">
											<div class="widgetButtons" style="text-align: left">                        
								   
												<div class="bb" id="thumbnails">
												<a href="#" class="tipb" title="" data-original-title="Add new">
												<span class="ibw-plus"></span></a>
												</div>
											</div>
											<?php echo $this->forminput($form->get('image'))?>
											<input type="button" value="Chọn ảnh"
									onclick="BrowseServer( 'Images:/', 'xImagePath' );" />
										</div>
										<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span12">
									<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Mô tả</h4>
									<?php echo $this->formtextarea($form->get('description'))?>						</div>
								<div class="clear"></div>
							</div>
							
							<div class="footer tar">
                                <button class="btn"> Thêm album </button>
							</div>	
                    </div>
                </div>                                
                </form>
            </div>
            <div class="row-fluid">
                
                <div class="span12">                    
                    <div class="head">
                        <div class="isw-grid"></div>
                        <h1>Danh sách</h1>
						<ul class="buttons">
                            <li><a href="#" class="isw-download"></a></li>                                                        
                            <li><a href="#" class="isw-attachment"></a></li>
                            <li>
                                <a href="#" class="isw-settings"></a>
                                <ul class="dd-list">
                                    <li><a href="#"><span class="isw-plus"></span> New document</a></li>
                                    <li><a href="#"><span class="isw-edit"></span> Edit</a></li>
                                    <li><a href="#"><span class="isw-delete"></span> Delete</a></li>
                                </ul>
                            </li>
                        </ul>               
                        <div class="clear"></div>
                    </div>
					
                    <div class="block-fluid table-sorting">
                        <table cellpadding="0" cellspacing="0" width="100%" class="table" >
                            <thead>
                                <tr>
                                    <th width="5%"><input type="checkbox" name="checkall"/></th>
                                    <th width="5%">STT</th>
									<th width="10%">Ảnh đại diện</th>
									<th width="20%">Tên album</th>
									<th width="15%">Items</th>
                                    <th width="15%">Trạng thái</th>
									<th width="10%">Hành động</th>                                    
                                </tr>
                            </thead>
                            <tbody class="category">
                            <?php foreach ($Albumanh as $Albumanhs):?>
                                <tr class="edit_<?php echo $Albumanhs->id ?>">
                                    <td><input type="checkbox" name="checkbox"/></td>
                                    <td><?php echo $Albumanhs->id ?></td>
                                    <td><img src="<?php echo $Albumanhs->image  ?>" /></td>
                                    <td><?php echo $Albumanhs->name  ?></td>
                                    <td><a href="<?php echo $this->url('albumanh', array('action'=>'item','id'=>$Albumanhs->id))?>">( <?php echo $count[$Albumanhs->id]?> ) Click để xem danh sách ảnh</a></td>
                                    <td><select class="active" disabled>
                                    <option value="0" <?php if($Albumanhs->active == 0 ) echo "selected"?>>Ngưng</option>
                                    <option value="1" <?php if($Albumanhs->active == 1 ) echo "selected"?>>Hoạt động</option>
                                    </select></td>
                                    <td class="action_hanhdong">
										<a href="javascript::void()" title="Sửa" data-href="<?php echo $this->url('albumanh', array('action'=>'edit','id'=>$Albumanhs->id))?>" id="dialogBtn"><i class="fa fa-pencil-square-o"></i></a>
										<a href="" class="delete" data-href="<?php echo $this->url('albumanh', array('action'=>'delete','id'=>$Albumanhs->id))?>"><i class="fa fa-trash-o" title="Xóa"></i></a>
									</td>
                                </tr>
                             <?php endforeach;?>
								
                            </tbody>
                        </table>
                        <div class="clear"></div>
                    </div>
                </div>                                
                
            </div> 
            
            <div class="dr"><span></span></div>            
            
        </div>
        <script type='text/javascript'>
		$(document).ready(function(){
			$("#dialog").dialog({
				autoOpen: false,
				modal: true,
				height: 600,
				width: 960,
				show: 'blind',
				
				 
			});

			$('#dialogBtn').click(function(){
				var ahref = $(this).attr('data-href');
				$('#dialog').dialog('open');
				$('#myIframe').attr('src', ahref);
			});
			
			$("#taomenu1").dialog({
				autoOpen: false,
				modal: true,
				height: 500,
				width: 400,
				show: 'blind',
				
				 
			});

			$('#taomenu').click(function(){
				var ahref = $(this).attr('data-href');
				$('#taomenu1').dialog('open');
				$('#myIframe1').attr('src', 'add');
			});

					$('body').on('click','a.delete', function()
					{
						var r = confirm("Nếu xóa thì các ảnh trong album sẽ bị xóa. Bạn có chắc chắn xóa thông tin này");
						if (r == true) {
							var URL = $(this).attr("data-href");
							
							$.ajax({
								type: "POST",
								url: URL,
								cache: false,
								success: function(html){
									
									notify_s('Thông báo','Bạn đã xóa thành công');
									
								}
							})
							$(this).closest("tbody.category tr").fadeOut(function(){$(this).remove()});
						} 
						
					});

			
		})
	</script>
	<div id="dialog">
			<iframe id="myIframe" src="" width="100%" height="100%" style="border: 1px solid #ccc"></iframe>
	</div>
	<div id="taomenu1">
			<iframe id="myIframe1" src="" width="100%" height="100%" style="border: 1px solid #ccc"></iframe>
	</div>
    <script type="text/javascript">
			function closeModal() {
			  $("#dialog").dialog("close");
			}

			function closeModal1() {
			  $("#taomenu1").dialog("close");
			}
	</script>