<script type="text/javascript">

function BrowseServer( startupPath, functionData )
{
	// You can use the "CKFinder" class to render CKFinder in a page:
	var finder = new CKFinder();

	// The path for the installation of CKFinder (default = "/ckfinder/").
	finder.basePath = '../';

	//Startup path in a form: "Type:/path/to/directory/"
	finder.startupPath = startupPath;

	// Name of a function which is called when a file is selected in CKFinder.
	finder.selectActionFunction = SetFileField;

	// Additional data to be passed to the selectActionFunction in a second argument.
	// We'll use this feature to pass the Id of a field that will be updated.
	finder.selectActionData = functionData;

	// Name of a function which is called when a thumbnail is selected in CKFinder.
	finder.selectActionFunction = ShowThumbnails;

	// Launch CKFinder
	finder.popup();
}

// This is a sample function which is called when a file is selected in CKFinder.
function SetFileField( fileUrl, data )
{
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

// This is a sample function which is called when a thumbnail is selected in CKFinder.
function ShowThumbnails( fileUrl, data )
{

	// this = CKFinderAPI
	var sFileName = this.getSelectedFile().name;
	document.getElementById('thumbnails').innerHTML = '';
	document.getElementById('thumbnails').innerHTML +=
			
			'<div class="thumb">' +
				'<img src="' + fileUrl + '" />' +
				'<div class="caption">' +
					'<a href="' + data["fileUrl"] + '" target="_blank">' + sFileName + '</a> (' + data["fileSize"] + 'KB)' +
				'</div>' +
			'</div>';

	
	// It is not required to return any value.
	// When false is returned, CKFinder will not close automatically.
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

function BrowseServer2( startupPath, functionData )
{
	// You can use the "CKFinder" class to render CKFinder in a page:
	var finder = new CKFinder();

	// The path for the installation of CKFinder (default = "/ckfinder/").
	finder.basePath = '../';

	//Startup path in a form: "Type:/path/to/directory/"
	finder.startupPath = startupPath;

	// Name of a function which is called when a file is selected in CKFinder.
	finder.selectActionFunction = SetFileField2;

	// Additional data to be passed to the selectActionFunction in a second argument.
	// We'll use this feature to pass the Id of a field that will be updated.
	finder.selectActionData = functionData;

	// Name of a function which is called when a thumbnail is selected in CKFinder.
	finder.selectActionFunction = ShowThumbnails2;

	// Launch CKFinder
	finder.popup();
}

// This is a sample function which is called when a file is selected in CKFinder.
function SetFileField2( fileUrl, data )
{
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

// This is a sample function which is called when a thumbnail is selected in CKFinder.
function ShowThumbnails2( fileUrl, data )
{

	// this = CKFinderAPI
	var sFileName = this.getSelectedFile().name;
	document.getElementById('thumbnails2').innerHTML = '';
	document.getElementById('thumbnails2').innerHTML +=
			
			'<div class="thumb">' +
				'<img src="' + fileUrl + '" />' +
				'<div class="caption">' +
					'<a href="' + data["fileUrl"] + '" target="_blank">' + sFileName + '</a> (' + data["fileSize"] + 'KB)' +
				'</div>' +
			'</div>';

	
	// It is not required to return any value.
	// When false is returned, CKFinder will not close automatically.
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

function BrowseServer3( startupPath, functionData )
{
	// You can use the "CKFinder" class to render CKFinder in a page:
	var finder = new CKFinder();

	// The path for the installation of CKFinder (default = "/ckfinder/").
	finder.basePath = '../';

	//Startup path in a form: "Type:/path/to/directory/"
	finder.startupPath = startupPath;

	// Name of a function which is called when a file is selected in CKFinder.
	finder.selectActionFunction = SetFileField3;

	// Additional data to be passed to the selectActionFunction in a second argument.
	// We'll use this feature to pass the Id of a field that will be updated.
	finder.selectActionData = functionData;

	// Name of a function which is called when a thumbnail is selected in CKFinder.
	finder.selectActionFunction = ShowThumbnails3;

	// Launch CKFinder
	finder.popup();
}

// This is a sample function which is called when a file is selected in CKFinder.
function SetFileField3( fileUrl, data )
{
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

// This is a sample function which is called when a thumbnail is selected in CKFinder.
function ShowThumbnails3( fileUrl, data )
{

	// this = CKFinderAPI
	var sFileName = this.getSelectedFile().name;
	document.getElementById('thumbnails3').innerHTML = '';
	document.getElementById('thumbnails3').innerHTML +=
			
			'<div class="thumb">' +
				'<img src="' + fileUrl + '" />' +
				'<div class="caption">' +
					'<a href="' + data["fileUrl"] + '" target="_blank">' + sFileName + '</a> (' + data["fileSize"] + 'KB)' +
				'</div>' +
			'</div>';

	
	// It is not required to return any value.
	// When false is returned, CKFinder will not close automatically.
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}


</script>
<script type="text/javascript">
				$(document).ready(function(){
					$("#validation").submit(function(){
					    parent.closeModal();
					});
				})
			</script>

<div class="row-fluid">
               	<?php
				$form = $this->form;
				$form->setAttributes ( array (
				'id' => 'validation') );
				$form->setAttribute ( 'action', $this->url ( 'theloaitin', array (
				'action' => 'edit','id'=>$this->id ) ) );
				$form->prepare ();
				echo $this->form ()->openTag ( $form );
				?>
                <div class="span12">
              	<?php echo $this->formhidden($form->get('id')); ?>
                <?php echo $this->formhidden($form->get('active'))?> 
                
                    <div class="block-fluid tabs">
                        
                        <ul>
                            <li><a href="#tabs-1">Thông tin danh mục</a></li>
                            <li><a href="#tabs-2">Hình ảnh</a></li>
                            <li><a href="#tabs-3">SEO</a></li>
                        </ul>                        
                        
                                                
                        
                        <div id="tabs-1">
                            <div class="block-fluid">                        
								
									
								<div class="row-form">
									<div class="span2">Tên danh mục (*) :</div>
									<div class="span3"><?php echo $this->forminput($form->get('name'))?> <span>Example: Điện thoại</span>
									<?php echo $this->formElementErrors($form->get('name'));?>
									</div>
									<div class="span2 offset1">Đường dẫn tối ưu (*) :</div>
									<div class="span3"><?php echo $this->forminput($form->get('alias'))?> <span>Example: dien-thoai</span></div>
									<div class="clear"></div>
								</div>
								
								<div class="row-form">
									<div class="span2">Tên danh mục ( Tiếng Anh ) :</div>
									<div class="span3"><?php echo $this->forminput($form->get('name_en'))?> <span>Example: Phone</span>
									<?php echo $this->formElementErrors($form->get('name_en'));?>
									</div>
									<div class="clear"></div>
								</div>
								
								<div class="row-form">
									<div class="span2">Thứ tự :</div>
									<div class="span3">
									<?php echo $this->forminput($form->get('order'))?>
									<br />
									<span>Example: 1 -> N </span></div>
									<div class="span2 offset1">Danh mục cha :</div>
									<div class="span3">
										<?php echo $this->formselect($form->get('parent'))?>
	
									<span>Click chọn danh mục cấp cha </span></div>
									<div class="clear"></div>
								</div>
								
								<div class="row-form">
									<div class="span2">Hiển thị trang chủ :</div>
									<div class="span3"><?php echo $this->formcheckbox($form->get('cateindex'))?> <span> Click để hiện thị danh mục ngoài trang chủ  </span></div>
									<div class="span2 offset1">Số lượng  :</div>
									<div class="span3">
										<?php echo $this->forminput($form->get('quantity'))?>

									<span>Chọn số lượng được hiển thị ngoài trang chủ </span></div>
									<div class="clear"></div>
								</div>
								<div class="row-form">
								<div class="span12">
									<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Mô tả</h4>
									<?php echo $this->formtextarea($form->get('description'))?>
								</div>
								<div class="clear"></div>
								</div>
				
							</div>
                        </div>
						
						
                                                
                        <div id="tabs-2">
                            <div class="block">
						
							
							<div class="row-form">
								<div class="span3"><h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Ảnh đại diện </h4>
									<div class="widgetButtons" style="text-align: left">                        
							   
										<div class="bb" id="thumbnails">
	                           			<div class="thumb"><img src="<?php echo $form->image ?>">
	                           			
	                           			</div></div>
									</div>
									<?php echo $this->forminput($form->get('image'))?>
									<input type="button" value="Chọn ảnh"
									onclick="BrowseServer( 'Images:/', 'xImagePath' );" />
								</div>
								<div class="span3 offset1"><h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Biểu tượng </h4>
									<div class="widgetButtons" style="text-align: left">                        
								   		<div class="bb" id="thumbnails2">
	                           			<div class="thumb"><img src="<?php echo $form->icon ?>">
	                           			
	                           			</div></div>
									</div>
									<?php echo $this->forminput($form->get('icon'))?>
									<input type="button" value="Chọn ảnh"
									onclick="BrowseServer2( 'Images:/', 'xImagePath2' );" />
								</div>
								<div class="span3 offset1"><h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Ảnh nền </h4>
									<div class="widgetButtons" style="text-align: left">                        
							   			<div class="bb" id="thumbnails3">
	                           			<div class="thumb"><img src="<?php echo $form->background ?>">
	                           			
	                           			</div></div>
									</div>
									<?php echo $this->forminput($form->get('background'))?>
									<input type="button" value="Chọn ảnh"
									onclick="BrowseServer3( 'Images:/', 'xImagePath3' );" />
								</div>
								<div class="clear"></div>
							</div>
							
							
							
							
							</div>
                        </div>
						
						
						<div id="tabs-3">
                            <div class="block">
							<div class="row-form">
							<div class="span12">
							<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Tiêu đề </h4>
							<?php echo $this->forminput($form->get('seotitle'))?> <span>
							
							</div>
							<div class="clear"></div>
							</div>
							<div class="row-form">
							
							<div class="span12"><h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Mô tả nội dung </h4>
							<?php echo $this->formtextarea($form->get('meta'))?>
							</div>
							<div class="clear"></div>
							</div>
							<div class="row-form">
							<div class="span12">
							<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Từ khóa </h4>
							<?php echo $this->forminput($form->get('keyword'))?> <span>
							
							</div>
							<div class="clear"></div>
							</div>
							
							</div>
                        </div>
						<div class="footer tar">
                              <input type="submit" value="Thêm danh mục " class="btn themdanhmuc"/> 
								</div>	
                        
                    </div>
                </div>                                
                </form>
            </div> 
            