<script type="text/javascript">

function BrowseServer( startupPath, functionData )
{
	// You can use the "CKFinder" class to render CKFinder in a page:
	var finder = new CKFinder();

	// The path for the installation of CKFinder (default = "/ckfinder/").
	finder.basePath = '../';

	//Startup path in a form: "Type:/path/to/directory/"
	finder.startupPath = startupPath;

	// Name of a function which is called when a file is selected in CKFinder.
	finder.selectActionFunction = SetFileField;

	// Additional data to be passed to the selectActionFunction in a second argument.
	// We'll use this feature to pass the Id of a field that will be updated.
	finder.selectActionData = functionData;

	// Name of a function which is called when a thumbnail is selected in CKFinder.
	finder.selectActionFunction = ShowThumbnails;

	// Launch CKFinder
	finder.popup();
}

// This is a sample function which is called when a file is selected in CKFinder.
function SetFileField( fileUrl, data )
{
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

// This is a sample function which is called when a thumbnail is selected in CKFinder.
function ShowThumbnails( fileUrl, data )
{

	// this = CKFinderAPI
	var sFileName = this.getSelectedFile().name;
	document.getElementById('thumbnails').innerHTML = '';
	document.getElementById('thumbnails').innerHTML +=
			
			'<div class="thumb">' +
				'<img src="' + fileUrl + '" />' +
				'<div class="caption">' +
					'<a href="' + data["fileUrl"] + '" target="_blank">' + sFileName + '</a> (' + data["fileSize"] + 'KB)' +
				'</div>' +
			'</div>';

	
	// It is not required to return any value.
	// When false is returned, CKFinder will not close automatically.
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

function BrowseServer2( startupPath, functionData )
{
	// You can use the "CKFinder" class to render CKFinder in a page:
	var finder = new CKFinder();

	// The path for the installation of CKFinder (default = "/ckfinder/").
	finder.basePath = '../';

	//Startup path in a form: "Type:/path/to/directory/"
	finder.startupPath = startupPath;

	// Name of a function which is called when a file is selected in CKFinder.
	finder.selectActionFunction = SetFileField2;

	// Additional data to be passed to the selectActionFunction in a second argument.
	// We'll use this feature to pass the Id of a field that will be updated.
	finder.selectActionData = functionData;

	// Name of a function which is called when a thumbnail is selected in CKFinder.
	finder.selectActionFunction = ShowThumbnails2;

	// Launch CKFinder
	finder.popup();
}

// This is a sample function which is called when a file is selected in CKFinder.
function SetFileField2( fileUrl, data )
{
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

// This is a sample function which is called when a thumbnail is selected in CKFinder.
function ShowThumbnails2( fileUrl, data )
{

	// this = CKFinderAPI
	var sFileName = this.getSelectedFile().name;
	document.getElementById('thumbnails2').innerHTML = '';
	document.getElementById('thumbnails2').innerHTML +=
			
			'<div class="thumb">' +
				'<img src="' + fileUrl + '" />' +
				'<div class="caption">' +
					'<a href="' + data["fileUrl"] + '" target="_blank">' + sFileName + '</a> (' + data["fileSize"] + 'KB)' +
				'</div>' +
			'</div>';

	
	// It is not required to return any value.
	// When false is returned, CKFinder will not close automatically.
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

function BrowseServer3( startupPath, functionData )
{
	// You can use the "CKFinder" class to render CKFinder in a page:
	var finder = new CKFinder();

	// The path for the installation of CKFinder (default = "/ckfinder/").
	finder.basePath = '../';

	//Startup path in a form: "Type:/path/to/directory/"
	finder.startupPath = startupPath;

	// Name of a function which is called when a file is selected in CKFinder.
	finder.selectActionFunction = SetFileField3;

	// Additional data to be passed to the selectActionFunction in a second argument.
	// We'll use this feature to pass the Id of a field that will be updated.
	finder.selectActionData = functionData;

	// Name of a function which is called when a thumbnail is selected in CKFinder.
	finder.selectActionFunction = ShowThumbnails3;

	// Launch CKFinder
	finder.popup();
}

// This is a sample function which is called when a file is selected in CKFinder.
function SetFileField3( fileUrl, data )
{
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

// This is a sample function which is called when a thumbnail is selected in CKFinder.
function ShowThumbnails3( fileUrl, data )
{

	// this = CKFinderAPI
	var sFileName = this.getSelectedFile().name;
	document.getElementById('thumbnails3').innerHTML = '';
	document.getElementById('thumbnails3').innerHTML +=
			
			'<div class="thumb">' +
				'<img src="' + fileUrl + '" />' +
				'<div class="caption">' +
					'<a href="' + data["fileUrl"] + '" target="_blank">' + sFileName + '</a> (' + data["fileSize"] + 'KB)' +
				'</div>' +
			'</div>';

	
	// It is not required to return any value.
	// When false is returned, CKFinder will not close automatically.
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}


</script>
        <?php echo $this->render('layout/bread.phtml')?>
        
        <div class="workplace">
			<div class="page-header">
                    <h1>Quản lý <small>danh mục tin tức</small></h1>
            </div>
            <?php echo $this->render('layout/menutintuc.phtml')?>
            
            <div class="row-fluid">
               	<?php
				$form = $this->form;
				$form->setAttributes ( array (
				'id' => 'validation' ) );
				$form->setAttribute ( 'action', $this->url ( 'theloaitin', array (
				'action' => 'list' ) ) );
				$form->prepare ();
				echo $this->form ()->openTag ( $form );
				?>
                <div class="span12">
                <input type="hidden" name="id" />    
                <?php echo $this->formhidden($form->get('active'))?> 
                    <div class="head">
                        <div class="isw-list"></div>
                        <h1>Sản phẩm mới</h1>
						<ul class="buttons">
                                <li><a href="#" class="isw-ok"></a></li>
                                
                            </ul>
                        <div class="clear"></div>
                    </div>
                    <div class="block-fluid tabs">
                        
                        <ul>
                            <li><a href="#tabs-1">Thông tin danh mục</a></li>
                            <li><a href="#tabs-2">Hình ảnh</a></li>
                            <li><a href="#tabs-3">SEO</a></li>
                        </ul>                        
                        
                                                
                        
                        <div id="tabs-1">
                            <div class="block-fluid">                        
								
									
								<div class="row-form">
									<div class="span2">Tên danh mục (*) :</div>
									<div class="span3"><?php echo $this->forminput($form->get('name'))?> <span>Example: Điện thoại</span>
									<?php echo $this->formElementErrors($form->get('name'));?>
									</div>
									<div class="span2 offset1">Đường dẫn tối ưu (*) :</div>
									<div class="span3"><?php echo $this->forminput($form->get('alias'))?> <span>Example: dien-thoai</span></div>
									<div class="clear"></div>
								</div>
								<div class="row-form">
									<div class="span2">Tên danh mục ( Tiếng Anh ) :</div>
									<div class="span3"><?php echo $this->forminput($form->get('name_en'))?> <span>Example: Phone</span>
									<?php echo $this->formElementErrors($form->get('name_en'));?>
									</div>
									<div class="clear"></div>
								</div>
								
								<div class="row-form">
									<div class="span2">Thứ tự :</div>
									<div class="span3">
									<?php echo $this->forminput($form->get('order'))?>
									<br />
									<span>Example: 1 -> N </span></div>
									<div class="span2 offset1">Danh mục cha :</div>
									<div class="span3">
										<?php echo $this->formselect($form->get('parent'))?>
	
									<span>Click chọn danh mục cấp cha </span></div>
									<div class="clear"></div>
								</div>
								
								<div class="row-form">
									<div class="span2">Hiển thị trang chủ :</div>
									<div class="span3"><?php echo $this->formcheckbox($form->get('cateindex'))?> <span> Click để hiện thị danh mục ngoài trang chủ  </span></div>
									<div class="span2 offset1">Số lượng  :</div>
									<div class="span3">
										<?php echo $this->forminput($form->get('quantity'))?>

									<span>Chọn số lượng được hiển thị ngoài trang chủ </span></div>
									<div class="clear"></div>
								</div>
								<div class="row-form">
								<div class="span12">
									<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Mô tả</h4>
									<?php echo $this->formtextarea($form->get('description'))?>
								</div>
								<div class="clear"></div>
								</div>
				
							</div>
                        </div>
						
						
                                                
                        <div id="tabs-2">
                            <div class="block">
						
							
							<div class="row-form">
								<div class="span3"><h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Ảnh đại diện </h4>
									<div class="widgetButtons" style="text-align: left">                        
							   
										<div class="bb" id="thumbnails">
										<a href="#" class="tipb" title="" data-original-title="Add new">
										<span class="ibw-plus"></span></a>
										</div>
									</div>
									<?php echo $this->forminput($form->get('image'))?>
									<input type="button" value="Chọn ảnh"
									onclick="BrowseServer( 'Images:/', 'xImagePath' );" />
								</div>
								<div class="span3 offset1"><h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Biểu tượng </h4>
									<div class="widgetButtons" style="text-align: left">                        
							   
										<div class="bb" id="thumbnails2"><a href="#" class="tipb" title="" data-original-title="Add new">
										<span class="ibw-plus"></span></a>
										</div>
									</div>
									<?php echo $this->forminput($form->get('icon'))?>
									<input type="button" value="Chọn ảnh"
									onclick="BrowseServer2( 'Images:/', 'xImagePath2' );" />
								</div>
								<div class="span3 offset1"><h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Ảnh nền </h4>
									<div class="widgetButtons" style="text-align: left">                        
							   
										<div class="bb" id="thumbnails3"><a href="#" class="tipb" title="" data-original-title="Add new">
										<span class="ibw-plus"></span></a>
										</div>
									</div>
									<?php echo $this->forminput($form->get('background'))?>
									<input type="button" value="Chọn ảnh"
									onclick="BrowseServer3( 'Images:/', 'xImagePath3' );" />
								</div>
								<div class="clear"></div>
							</div>
							
							
							
							
							</div>
                        </div>
						
						
						<div id="tabs-3">
                            <div class="block">
							<div class="row-form">
							<div class="span12">
							<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Tiêu đề </h4>
							<?php echo $this->forminput($form->get('seotitle'))?> <span>
							
							</div>
							<div class="clear"></div>
							</div>
							<div class="row-form">
							
							<div class="span12"><h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Mô tả nội dung </h4>
							<?php echo $this->formtextarea($form->get('meta'))?>
							</div>
							<div class="clear"></div>
							</div>
							<div class="row-form">
							<div class="span12">
							<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Từ khóa </h4>
							<?php echo $this->forminput($form->get('keyword'))?> <span>
							
							</div>
							<div class="clear"></div>
							</div>
							
							</div>
                        </div>
						<div class="footer tar">
                                <button class="btn"> Thêm danh mục </button>
								</div>	
                        
                    </div>
                </div>                                
                </form>
            </div> 
            <div class="row-fluid">
                
                <div class="span12">                    
                    <div class="head">
                        <div class="isw-grid"></div>
                        <h1>Danh sách</h1>
						<ul class="buttons">
                            <li><a href="#" class="isw-download"></a></li>                                                        
                            <li><a href="#" class="isw-attachment"></a></li>
                            <li>
                                <a href="#" class="isw-settings"></a>
                                <ul class="dd-list">
                                    <li><a href="#"><span class="isw-plus"></span> New document</a></li>
                                    <li><a href="#"><span class="isw-edit"></span> Edit</a></li>
                                    <li><a href="#"><span class="isw-delete"></span> Delete</a></li>
                                </ul>
                            </li>
                        </ul>               
                        <div class="clear"></div>
                    </div>
					
                    <div class="block-fluid table-sorting">
                        <table cellpadding="0" cellspacing="0" width="100%" class="table" id="tSortable">
                            <thead>
                                <tr>
                                    <th width="5%"><input type="checkbox" name="checkall"/></th>
                                    <th width="5%">STT</th>
									<th width="10%">Ảnh đại diện</th>
									<th width="15%">Tên danh mục</th>
									<th width="15%">Đường dẫn tối ưu</th>
                                    <th width="15%">SL hiện trang chủ</th>
									<th width="15%">Hiển thị trang chủ</th>
                                    <th width="10%">Tình trạng</th>
									<th width="10%">Hành động</th>                                    
                                </tr>
                            </thead>
                            <tbody class="category">
                            <?php foreach ($Theloaitin as $Theloaitins):?>
                                <tr>
                                    <td><input type="checkbox" name="checkbox"/></td>
                                    <td><?php echo $Theloaitins->id?></td>
                                    <td><img src="<?php echo $Theloaitins->image ?>" width="100"  /></td>
                                    <td><?php echo $Theloaitins->name ?></td>
                                    <td><?php echo $Theloaitins->alias ?></td>
									<td><?php echo $Theloaitins->quantity?></td>
                                    <td><?php if($Theloaitins->cateindex == 1) echo "Có"; else echo "Không" ;?></td>
                                    <td><?php if($Theloaitins->active == 1) echo "Hoạt động"; else echo "Tạm dừng" ;?></td>
                                    <td class="action_hanhdong">
										<a href="javascript::void()" title="Sửa" data-href="<?php echo $this->url('theloaitin', array('action'=>'edit','id'=>$Theloaitins->id))?>" id="dialogBtn"><i class="fa fa-pencil-square-o"></i></a>
										<a data-href="<?php echo $this->url('theloaitin', array('action'=>'delete','id'=>$Theloaitins->id))?>" href="javascript::void()" class="delete"><i class="fa fa-trash-o" title="Xóa"></i></a>
									</td>
                                    
                                </tr>
                            <?php endforeach;?>
                                   
                            </tbody>
                        </table>
                        <div class="clear"></div>
                    </div>
                </div>                                
                
            </div>            
            
            <div class="dr"><span></span></div>            
           
             
        </div>
        <script type='text/javascript'>
		$(document).ready(function(){
			$("#dialog").dialog({
				autoOpen: false,
				modal: true,
				height: 600,
				width: 960,
				show: 'blind',
				
				 
			});

			
			$('body').on('click','a#dialogBtn', function(){
				var ahref = $(this).attr('data-href');
				$('#dialog').dialog('open');
				$('#myIframe').attr('src', ahref);
				
			})
			
			$('body').on('click','a.delete', function()
			{
				var r = confirm("Nếu xóa danh mục sản phẩm thì tấc cả sản phẩm thuộc danh mục đó sẽ bị xóa . Bạn chắc chắn thực hiện điều đó");
				if (r == true) {
					var URL = $(this).attr("data-href");
					
					$.ajax({
						type: "POST",
						url: URL,
						cache: false,
						success: function(html){
							
							notify_s('Thông báo','Bạn đã xóa thành công');
							
						}
					})
					$(this).closest("tbody.category tr").fadeOut(function(){$(this).remove()});
				} 
				
			});
		})
	</script>
	<div id="dialog">
			<iframe id="myIframe" src="" width="100%" height="100%" style="border: 1px solid #ccc"></iframe>
	</div>
			<script type="text/javascript">
			function closeModal() {
			    $("#dialog").dialog("close");
			}
			</script>