<div class="art-blockheader">
	<h4 class="t" style="font-size:24px; margin-top:16px">Giỏ hàng của bạn</h4>
</div>
<div class="art-content-layout">
  <div class="art-content-layout-row">
    <div class="art-layout-cell layout-item-2" style="width: 100%;" >
      <div align="center" style="color: black;">
      <form action="<?php echo $this->url('giohang',array('action'=>'list'));?>" method="post">
	<?php 
		if(isset($ds_sp))
		{
    ?>
		   <table width="98%" align='center' cellspacing="0" cellpadding="5px">
              <tr bgcolor="#FFE7D5" align="center">
                <td>Mã sản phẩm</td><td>Tên sản phẩm</td><td>Đơn giá</td><td>Số lượng</td><td>Hình</td><td>Xóa</td>
              </tr>
    <?php
        $i=1;
		 foreach($ds_sp as $row)
		 {
			echo '<tr>';
			echo    '<td align="center">';
            echo        $row['product_id'];
            echo    '<input type="hidden" name="id'.$row['id'].'" value="'.$row['id'].'"/>
    				 <input type="hidden" name="price'.$row['id'].'" value="'.$row['price'].'"/>';
            echo    '</td>';
            echo    '<td>'.$row['product_name'].'</td>';
            echo    '<td>'.number_format($row['price']).'</td>';
            echo    '<td><input type="text" name="qty'.$row['id'].'" value="'.$row['qty'].'" style="text-align:center"/></td>';
            echo    '<td><img src="'.$this->basePath()."/hinh_san_pham/".$row['image'].'" width="70px" height="80px"/></td>';
            echo    '<td><input type="checkbox" value="'.$row['id'].'" name="xoa'.$row['id'].'"/></td>';
            echo '</tr>';
            $i++;
         }        
	?>
        <tr><td colspan="6"  align="center">
            <input class="art-button" type="submit" name="submit" value="Cập nhật"/>
            <input class="art-button" type="button" name="boqua" value="Tiếp tục mua hàng" onclick="window.location.href = '<?php echo $this->url('san-pham',array('action'=>'allproducts'));?>'"/>
            </td>
        </tr>
        </table>
    </form>
    <?php
		}
        else
        {
            echo '<h3 align="center">Bạn chưa chọn sản phẩm nào cho giỏ hàng</h3><br>';  
            echo '<input class="art-button" type="button" name="boqua" value="Tiếp tục mua hàng" onclick="window.location.href = \''. $this->url('san-pham',array('action'=>'allproducts')).'\'"/>';
        }
                          
	?>
       </div>
    </div>
  </div>
</div>
