<div class="row-fluid">
                    <div class="span12">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <div class="container">
                                   
                                    <div class="nav-collapse collapse navbar-responsive-collapse">
                                        <ul class="nav">
                                            <li><a href="<?php echo $this->url('sanpham',array('action'=>'add'))?>">Đăng sản phảm</a></li>
                                            <li><a href="#">Quản lý danh mục</a></li>
                                            <li class="active"><a href="<?php echo $this->url('sanpham',array('action'=>'list'))?>">Quản lý sản phẩm</a></li>
											<li><a href="#">Thông tin liên hệ</a></li>
                                            <li><a href="#">Cài đặt thah toán</a></li>
											<li><a href="#">Quán lý đơn hàng</a></li>
                                            <li><a href="#">Quản lý thông số</a></li>
                                            <li><a href="#">Quản lý nhà sản xuất</a></li>
                                        </ul>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>    
                    </div>
                </div>