


<div class="container">
        <div class="row">
  <?php
	$form = $this->form;
	$form->setAttribute ( 'action', $this->url ( 'customers', array (
	'action' => 'add' ) ) );
	$form->prepare ();
	echo $this->form ()->openTag ( $form );
	echo $this->formHidden ( $form->get ( 'customers_id' ) );
	
	?>          
            <!--  ==========  -->
            <!--  = Main content =  -->
            <!--  ==========  -->
            <section class="span12">
                
                <div class="checkout-container">
                    <div class="row">
                    	<div class="span10 offset1">
                    	    
                    	    <!--  ==========  -->
							<!--  = Header =  -->
							<!--  ==========  -->
                    		<header>
                    		    <div class="row">
                    		    	<div class="span2">
                    		    		<a href="index-2.html"><img src="images/logo-bw.png.pagespeed.ce.KeNq9wU_LZ.png" alt="Webmarket Logo" width="48" height="48"/></a>
                    		    	</div>
                    		    	<div class="span6">
                    		    	    <div class="center-align">
                    		    	        <h1><span class="light">Billing</span> &amp; Shipping Address</h1>
                    		    	    </div>
                    		    	</div>
                    		    	<div class="span2">
                    		    	    <div class="right-align">
                    		    	    	<img src="images/buttons/92x65xsecurity.jpg.pagespeed.ic.0kRRD5XXok.jpg" alt="Security Sign" width="92" height="65"/>
                    		    	    </div>
                    		    	</div>
                    		    </div>
                    		</header>
                    		
                    		<!--  ==========  -->
							<!--  = Steps =  -->
							<!--  ==========  -->
                    		<div class="checkout-steps">
                    		    <div class="clearfix">
                    		    	<div class="step done">
                    		    	    <div class="step-badge"><i class="icon-ok"></i></div>
                    		    	    <a href="checkout-step-1.html">Shopping Cart</a>
                    		    	</div>
                    		    	<div class="step active">
                    		    	    <div class="step-badge">2</div>
                    		    	    Shipping Address
                    		    	</div>
                    		    	<div class="step">
                                        <div class="step-badge">2</div>
                                        Payment Method
                                    </div>
                    		    	<div class="step">
                    		    	    <div class="step-badge">4</div>
                    		    	    Confirm &amp; Pay
                    		    	</div>
                    		    </div>
                    		</div> <!-- /steps -->
                    		
						    <!--  ==========  -->
							<!--  = Shipping addr form =  -->
							<!--  ==========  -->
							    
						    <form action="#" method="post" class="form-horizontal form-checkout">
                                <div class="control-group">
                                    <label class="control-label" for="firstName">Full Name<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <?php echo $this->formInput ( $form->get ( 'customers_name' ) );
										echo $this->formElementErrors ( $form->get ( 'customers_name' ) );
										?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="telephone">Telephone<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <?php echo $this->formInput ( $form->get ( 'phone_number' ) );
										echo $this->formElementErrors ( $form->get ( 'phone_number' ) );
										?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="email">Email<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <?php echo $this->formInput ( $form->get ( 'email' ) );
										echo $this->formElementErrors ( $form->get ( 'email' ) );
										?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="addr1">Address 1<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <?php echo $this->formInput ( $form->get ( 'delivery_address' ) );
										echo $this->formElementErrors ( $form->get ( 'delivery_address' ) );
										?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="addr2">Address 2</label>
                                    <div class="controls">
                                        <?php echo $this->formInput ( $form->get ( 'address' ) );
										echo $this->formElementErrors ( $form->get ( 'address' ) );
										?>
                                    </div>
                                </div>
                                
                            </form>
							
                            <hr/>
						    
						    <p class="right-align">
						        In the next step you will choose a payment method &nbsp; &nbsp;
						        
						        <input id="submitOrder" type="submit" class="btn btn-primary higher bold"
							value=" CONTINUE ">
						    </p>
							    
							    
                    	</div>
                    </div>
                </div>
                
                
            </section> <!-- /main content -->
        <?php echo $this->form()->closeTag() ?>
        </div>
    </div> <!-- /container -->