


<div class="container">
        <div class="row">

<?php
if (isset ( $ds_sp )) {
?>
<form name="cart_quantity"
		action="<?php echo $this->url('sanpham',array('action'=>'giohang'));?>"
		method="post">
<section class="span12">
                
                <div class="checkout-container">
                    <div class="row">
                    	<div class="span10 offset1">
                    	    
                    	    <!--  ==========  -->
							<!--  = Header =  -->
							<!--  ==========  -->
                    		<header>
                    		    <div class="row">
                    		    	<div class="span2">
                    		    		<a href="index-2.html"><img src="<?php echo $this->basepath()?>/images/logo-bw.png.pagespeed.ce.KeNq9wU_LZ.png" alt="Webmarket Logo" width="48" height="48"/></a>
                    		    	</div>
                    		    	<div class="span6">
                    		    	    <div class="center-align">
                    		    	        <h1><span class="light">Review</span> Shopping Cart</h1>
                    		    	    </div>
                    		    	</div>
                    		    	<div class="span2">
                    		    	    <div class="right-align">
                    		    	    	<img src="<?php echo $this->basepath()?>/images/buttons/92x65xsecurity.jpg.pagespeed.ic.0kRRD5XXok.jpg" alt="Security Sign" width="92" height="65"/>
                    		    	    </div>
                    		    	</div>
                    		    </div>
                    		</header>
                    		
                    		<!--  ==========  -->
							<!--  = Steps =  -->
							<!--  ==========  -->
                    		<div class="checkout-steps">
                    		    <div class="clearfix">
                    		    	<div class="step active">
                    		    	    <div class="step-badge">1</div>
                    		    	    Shopping Cart
                    		    	</div>
                    		    	<div class="step">
                    		    	    <div class="step-badge">3</div>
                    		    	    Shipping Address
                    		    	</div>
                    		    	<div class="step">
                                        <div class="step-badge">2</div>
                                        Payment Method
                                    </div>
                    		    	<div class="step">
                    		    	    <div class="step-badge">4</div>
                    		    	    Confirm &amp; Pay
                    		    	</div>
                    		    </div>
                    		</div> <!-- /steps -->
                    		
                    		<!--  ==========  -->
							<!--  = Selected Items =  -->
							<!--  ==========  -->
							<table class="table table-items">
							    <thead>
							    	<tr>
							    		<th colspan="2">Item</th>
							    		<th><div class="align-center">Quantity</div></th>
							    		<th><div class="align-right">Price</div></th>
							    	</tr>
							    </thead>
							    <tbody>
							         <?php foreach($ds_sp as $row) : ?>
										<?php
										echo '<input type="hidden" name="id' . $row->id . '" value="' . $row->id . '"/>
										<input type="hidden" name="price' . $row->id . '" value="' . $row->price . '"/>';
										?>
							        <tr>
							        	<td class="image"><img src="<?php echo $row->image ?>" alt="" width="124" height="124"/></td>
							        	<td class="desc"><?php echo $row->proname ?> <a title="Remove Item" class="icon-remove-sign" href="#"></a></td>
							        	<td class="qty">
							        	    <input type="text" class="tiny-size" value="<?php echo $row->qty?>" name="<?php echo 'qty' . $row->id ?>" />
					            	    </td>
							        	<td class="price">
							        	    $<?php echo $row->price ?>
							        	</td>
							        </tr>
							         <?php endforeach ?>
							        
							        							        <tr>
							        	<td colspan="2" rowspan="2">
							        	    <div class="alert alert-info">
                                                <button data-dismiss="alert" class="close" type="button">×</button>
                                                Shipping costs are calculated based on location. <a href="#">More information</a>
                                            </div>
							        	</td>
							        	<td class="stronger">Shipping:</td>
							        	<td class="stronger"><div class="align-right">$0</div></td>
							        </tr>
							        <tr>
							        	<td class="stronger">Subtotal:</td>
							        	<td class="stronger"><div class="size-16 align-right">$<?php echo number_format ($tong_tien)?></div></td>
							        </tr>
							    </tbody>
							</table>
							
							<hr/>
							
							<p class="right-align">
							    In the next step you will choose your shipping address &nbsp; &nbsp;
							    <input type="submit" class="btn btn-primary higher bold" value=" Update ">
							    <a href="<?php echo $this->url('customers', array('action'=>'add'))?>" class="btn btn-primary higher bold">CONTINUE</a>
							</p>
                    	</div>
                    </div>
                </div>
                
                
            </section> <!-- /main content -->
            </form>
 <?php } ?>
 </div>
 </div>