<!--  ==========  -->
    <!--  = Breadcrumbs =  -->
    <!--  ==========  -->
    <div class="darker-stripe">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li>
                            <a href="">Trang chủ</a>
                        </li>
                        <li><span class="icon-chevron-right"></span></li>
                        <li>
                            <a href="shop.html">Shop</a>
                        </li>
                        <li><span class="icon-chevron-right"></span></li>
                        <li>
                            <a href="shop.html">Grid View</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="push-up blocks-spacer">
            <div class="row">

                <!--  ==========  -->
                <!--  = Sidebar =  -->
                <!--  ==========  -->
                <aside class="span3 left-sidebar" id="tourStep1">
                    <div class="sidebar-item sidebar-filters" id="sidebarFilters">

                        <!--  ==========  -->
                        <!--  = Sidebar Title =  -->
                        <!--  ==========  -->
                        <div class="underlined">
                            <h3><span class="light">Shop</span> by filters</h3>
                        </div>

                        <!--  ==========  -->
                        <!--  = Categories =  -->
                        <!--  ==========  -->
                        <div class="accordion-group" id="tourStep2">
                            <div class="accordion-heading">
                                <a class="accordion-toggle" data-toggle="collapse" href="#filterOne">Categories <b class="caret"></b></a>
                            </div>
                            <div id="filterOne" class="accordion-body collapse in">
                                <div class="accordion-inner">
                                    <a href="#" data-target=".filter--accessories" class="selectable"><i class="box"></i> Accessories</a>
<a href="#" data-target=".filter--bags, .filter--hats" class="selectable"><i class="box"></i> Bags &amp; Hats</a>
<a href="#" data-target=".filter--polo-shirts" class="selectable"><i class="box"></i> Polo Shirts</a>
<a href="#" data-target=".filter--shirts" class="selectable"><i class="box"></i> Shirts</a>
<a href="#" data-target=".filter--shoes, .filter--boots, .filter--trainers" class="selectable"><i class="box"></i> Shoes, Boots &amp; Trainers</a>
<a href="#" data-target=".filter--shorts" class="selectable"><i class="box"></i> Shorts</a>
<a href="#" data-target=".filter--suits, .filter--blazers" class="selectable"><i class="box"></i> Suits &amp; Blazers</a>
<a href="#" data-target=".filter--sunglasses" class="selectable"><i class="box"></i> Sunglasses</a>
<a href="#" data-target=".filter--swimwear" class="selectable"><i class="box"></i> Swimwear</a>
<a href="#" data-target=".filter--trousers, .filter--chinos" class="selectable"><i class="box"></i> Trousers &amp; Chinos</a>
<a href="#" data-target=".filter--t-shirts, .filter--vests" class="selectable"><i class="box"></i> T-Shirts &amp; Vests</a>
<a href="#" data-target=".filter--bags" class="selectable"><i class="box"></i> Bags</a>
<a href="#" data-target=".filter--underwear, .filter--socks" class="selectable"><i class="box"></i> Underwear &amp; Socks</a>
                                </div>
                            </div>
                        </div> <!-- /categories -->

                        <!--  ==========  -->
                        <!--  = Prices slider =  -->
                        <!--  ==========  -->
                        <div class="accordion-group">
                            <div class="accordion-heading">
                                <a class="accordion-toggle" data-toggle="collapse" href="#filterPrices">Price <b class="caret"></b></a>
                            </div>
                            <div id="filterPrices" class="accordion-body in collapse">
                                <div class="accordion-inner with-slider">
                                    <div class="jqueryui-slider-container">
                                        <div id="pricesRange"></div>
                                    </div>
                                    <input type="text" data-initial="432" class="max-val pull-right" disabled />
                                    <input type="text" data-initial="99" class="min-val" disabled />
                                </div>
                            </div>
                        </div> <!-- /prices slider -->

                        <!--  ==========  -->
                        <!--  = Size filter =  -->
                        <!--  ==========  -->
                        <div class="accordion-group" id="tourStep3">
                            <div class="accordion-heading">
                                <a class="accordion-toggle collapsed" data-toggle="collapse" href="#filterTwo">Size <b class="caret"></b></a>
                            </div>
                            <div id="filterTwo" class="accordion-body collapse">
                                <div class="accordion-inner">
                                    <a href="#" data-target="xs" data-type="size" class="selectable detailed"><i class="box"></i> XS</a>
<a href="#" data-target="s" data-type="size" class="selectable detailed"><i class="box"></i> S</a>
<a href="#" data-target="m" data-type="size" class="selectable detailed"><i class="box"></i> M</a>
<a href="#" data-target="l" data-type="size" class="selectable detailed"><i class="box"></i> L</a>
<a href="#" data-target="xl" data-type="size" class="selectable detailed"><i class="box"></i> XL</a>
<a href="#" data-target="xxl" data-type="size" class="selectable detailed"><i class="box"></i> XXL</a>
                                </div>
                            </div>
                        </div> <!-- /size filter -->

                        <!--  ==========  -->
                        <!--  = Color filter =  -->
                        <!--  ==========  -->
                        <div class="accordion-group">
                            <div class="accordion-heading">
                                <a class="accordion-toggle collapsed" data-toggle="collapse" href="#filterThree">Color <b class="caret"></b></a>
                            </div>
                            <div id="filterThree" class="accordion-body collapse">
                                <div class="accordion-inner">
                                    <a href="#" data-target="red" data-type="color" class="selectable detailed"><i class="box"></i> Red</a>
<a href="#" data-target="green" data-type="color" class="selectable detailed"><i class="box"></i> Green</a>
<a href="#" data-target="blue" data-type="color" class="selectable detailed"><i class="box"></i> Blue</a>
<a href="#" data-target="pink" data-type="color" class="selectable detailed"><i class="box"></i> Pink</a>
<a href="#" data-target="purple" data-type="color" class="selectable detailed"><i class="box"></i> Purple</a>
<a href="#" data-target="orange" data-type="color" class="selectable detailed"><i class="box"></i> Orange</a>
                                </div>
                            </div>
                        </div> <!-- /color filter -->

                        <!--  ==========  -->
                        <!--  = Brand filter =  -->
                        <!--  ==========  -->
                        <div class="accordion-group">
                            <div class="accordion-heading">
                                <a class="accordion-toggle collapsed" data-toggle="collapse" href="#filterFour">Brand <b class="caret"></b></a>
                            </div>
                            <div id="filterFour" class="accordion-body collapse">
                                <div class="accordion-inner">
                                    <a href="#" data-target="s-oliver" data-type="brand" class="selectable detailed"><i class="box"></i> S. Oliver</a>
<a href="#" data-target="nike" data-type="brand" class="selectable detailed"><i class="box"></i> Nike</a>
<a href="#" data-target="naish" data-type="brand" class="selectable detailed"><i class="box"></i> Naish</a>
<a href="#" data-target="adidas" data-type="brand" class="selectable detailed"><i class="box"></i> Adidas</a>
<a href="#" data-target="puma" data-type="brand" class="selectable detailed"><i class="box"></i> Puma</a>
<a href="#" data-target="shred" data-type="brand" class="selectable detailed"><i class="box"></i> Shred</a>
                                </div>
                            </div>
                        </div> <!-- /brand filter -->

                        <a href="#" class="remove-filter" id="removeFilters"><span class="icon-ban-circle"></span> Remove All Filters</a>

                    </div>
                </aside> <!-- /sidebar -->

                <!--  ==========  -->
                <!--  = Main content =  -->
                <!--  ==========  -->
                <section class="span9">

                    <!--  ==========  -->
                    <!--  = Title =  -->
                    <!--  ==========  -->
                    <div class="underlined push-down-20">
                        <div class="row">
                            <div class="span4">
                                <h3><span class="light">All</span> Products</h3>
                            </div>
                            <div class="span5 align-right sm-align-left">
                                <div class="form-inline sorting-by" id="tourStep4">
                                    <label for="isotopeSorting" class="black-clr">Sort:</label>
                                    <select id="isotopeSorting" class="span3">
                                        <option value='{"sortBy":"price", "sortAscending":"true"}'>By Price (Low to High) &uarr;</option>
                                        <option value='{"sortBy":"price", "sortAscending":"false"}'>By Price (High to Low) &darr;</option>
                                        <option value='{"sortBy":"name", "sortAscending":"true"}'>By Name (Low to High) &uarr;</option>
                                        <option value='{"sortBy":"name", "sortAscending":"false"}'>By Name (High to Low) &darr;</option>
                                        <option value='{"sortBy":"popularity", "sortAscending":"true"}'>By Popularity (Low to High) &uarr;</option>
                                        <option value='{"sortBy":"popularity", "sortAscending":"false"}'>By Popularity (High to Low) &darr;</option>
                                    </select>
                                </div>
                                <div class="view-switch">
                                    <a href="shop.html" class="btn btn-primary"><i class="icon-th"></i></a>
                                    <a href="shop-list-view.html" class="btn"><i class="icon-list"></i></a>
                                </div>
                            </div>
                        </div>
                    </div> <!-- /title -->

                    <!--  ==========  -->
                    <!--  = Products =  -->
                    <!--  ==========  -->
                    <div class="row popup-products">
                        <div id="isotopeContainer" class="isotope-container">


                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--polo-shirts" data-price="92" data-popularity="1" data-size="s|xxl" data-color="orange" data-brand="shred">
                                <div class="product">
                                    <div class="product-inner">
                                                                                    <div class="stamp green">New</div>
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-1.jpg.pagespeed.ce.Da1RubYOlL.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$92</h4>
                                            <h5 class="no-margin isotope--title">Vulputate Condimentum</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--bags" data-price="1545" data-popularity="3" data-size="s|m|xl|xxl" data-color="pink|purple" data-brand="shred">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-2.jpg.pagespeed.ce.EDQe3gHrr4.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1545</h4>
                                            <h5 class="no-margin isotope--title">Lorem Amet Consectetur Sed Condimentum</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--shirts" data-price="1041" data-popularity="3" data-size="xs|s|xl" data-color="green|blue" data-brand="s-oliver">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-3.jpg.pagespeed.ce.YWPViY8cOl.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1041</h4>
                                            <h5 class="no-margin isotope--title">Ipsum Consectetur Vivamus Nisi Duis</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--bags" data-price="736" data-popularity="5" data-size="xs|s|l|xxl" data-color="red|pink" data-brand="adidas">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-4.jpg.pagespeed.ce.bHDWegjUym.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$736</h4>
                                            <h5 class="no-margin isotope--title">Dolor Vivamus Sit Amet Ut</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--sunglasses" data-price="1581" data-popularity="1" data-size="xs|s|m|l" data-color="red|pink" data-brand="puma">
                                <div class="product">
                                    <div class="product-inner">
                                                                                    <div class="stamp green">New</div>
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-5.jpg.pagespeed.ce.4JLR3ZeQEC.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1581</h4>
                                            <h5 class="no-margin isotope--title">Tincidunt Vulputate Felis Duis</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--suits" data-price="1488" data-popularity="1" data-size="s|m|l" data-color="pink" data-brand="puma">
                                <div class="product">
                                    <div class="product-inner">
                                                                                    <div class="stamp green">New</div>
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-6.jpg.pagespeed.ce.XI0HBrK_zM.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1488</h4>
                                            <h5 class="no-margin isotope--title">Adipiscing Sit Condimentum Ut</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--swimwear" data-price="249" data-popularity="1" data-size="s|m|xxl" data-color="orange" data-brand="puma">
                                <div class="product">
                                    <div class="product-inner">
                                                                                    <div class="stamp green">New</div>
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-7.jpg.pagespeed.ce.HyGb3bENJ7.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$249</h4>
                                            <h5 class="no-margin isotope--title">Adipiscing Est Eros Feugiat Metus</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--trousers" data-price="699" data-popularity="5" data-size="xs|l|xl|xxl" data-color="purple" data-brand="s-oliver">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-8.jpg.pagespeed.ce.1vv0RltX3O.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$699</h4>
                                            <h5 class="no-margin isotope--title">Dolor Consectetur Adipiscing Felis Feugiat</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--socks" data-price="161" data-popularity="5" data-size="xs|m|xl|xxl" data-color="blue|pink" data-brand="s-oliver">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-9.jpg.pagespeed.ce.pgB4xkmiXd.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$161</h4>
                                            <h5 class="no-margin isotope--title">Consectetur Eros Ut</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--accessories" data-price="1055" data-popularity="1" data-size="l|xxl" data-color="blue" data-brand="s-oliver">
                                <div class="product">
                                    <div class="product-inner">
                                                                                    <div class="stamp green">New</div>
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-10.jpg.pagespeed.ce.I4zh8RM_A8.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1055</h4>
                                            <h5 class="no-margin isotope--title">Vel Felis Eros Condimentum</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--chinos" data-price="1027" data-popularity="3" data-size="xs|m|xl|xxl" data-color="green|purple" data-brand="puma">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-11.jpg.pagespeed.ce.dhG92Aw57l.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1027</h4>
                                            <h5 class="no-margin isotope--title">Elit Sed</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--underwear" data-price="1685" data-popularity="1" data-size="xs|m|xl" data-color="purple" data-brand="shred">
                                <div class="product">
                                    <div class="product-inner">
                                                                                    <div class="stamp green">New</div>
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-12.jpg.pagespeed.ce.v5dCplkcke.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1685</h4>
                                            <h5 class="no-margin isotope--title">Amet Vel Vel Nisi Duis</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--accessories" data-price="162" data-popularity="1" data-size="xs|m|xl" data-color="green" data-brand="s-oliver">
                                <div class="product">
                                    <div class="product-inner">
                                                                                    <div class="stamp green">New</div>
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-13.jpg.pagespeed.ce.n4S9S9r0y1.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$162</h4>
                                            <h5 class="no-margin isotope--title">Sit Elit Vivamus Est</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--suits" data-price="121" data-popularity="4" data-size="xs|m|l|xl" data-color="green|pink" data-brand="nike">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-14.jpg.pagespeed.ce.A3Xy9rc3L6.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$121</h4>
                                            <h5 class="no-margin isotope--title">Vel Metus</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--shirts" data-price="309" data-popularity="5" data-size="xs|s|m|xl" data-color="blue|pink" data-brand="naish">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-15.jpg.pagespeed.ce.2nvdKLn9rh.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$309</h4>
                                            <h5 class="no-margin isotope--title">Adipiscing Vivamus Metus</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--boots" data-price="822" data-popularity="3" data-size="xs|s|xl|xxl" data-color="pink|purple" data-brand="naish">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-16.jpg.pagespeed.ce.VRzvgI1NSs.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$822</h4>
                                            <h5 class="no-margin isotope--title">Sit Vel Est Condimentum</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--chinos" data-price="1249" data-popularity="5" data-size="xs|s|m|l" data-color="orange" data-brand="adidas">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-17.jpg.pagespeed.ce.7NZI69nMYk.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1249</h4>
                                            <h5 class="no-margin isotope--title">Dolor Amet</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--shorts" data-price="420" data-popularity="4" data-size="s|l" data-color="green" data-brand="shred">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-18.jpg.pagespeed.ce.fALt0fgNBe.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$420</h4>
                                            <h5 class="no-margin isotope--title">Adipiscing Neque Vel Nisi Vulputate</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--t-shirts" data-price="487" data-popularity="2" data-size="s|l" data-color="blue|pink" data-brand="s-oliver">
                                <div class="product">
                                    <div class="product-inner">
                                                                                    <div class="stamp red">Sold</div>
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-19.jpg.pagespeed.ce.5HEt0o7OAB.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$487</h4>
                                            <h5 class="no-margin isotope--title">Vivamus Vel</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--trainers" data-price="184" data-popularity="5" data-size="l|xxl" data-color="pink|purple" data-brand="shred">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-20.jpg.pagespeed.ce.F7BAxYDbLX.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$184</h4>
                                            <h5 class="no-margin isotope--title">Sit Consectetur Adipiscing Vivamus Metus</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--polo-shirts" data-price="421" data-popularity="5" data-size="m|xxl" data-color="red" data-brand="naish">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-21.jpg.pagespeed.ce.yYDOdqD4v1.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$421</h4>
                                            <h5 class="no-margin isotope--title">Ipsum Sit Neque Duis</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--t-shirts" data-price="286" data-popularity="5" data-size="xs|s|m" data-color="blue|pink" data-brand="puma">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-22.jpg.pagespeed.ce.z0Qhm86STl.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$286</h4>
                                            <h5 class="no-margin isotope--title">Lorem Adipiscing</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--t-shirts" data-price="576" data-popularity="2" data-size="m|l" data-color="red|purple" data-brand="puma">
                                <div class="product">
                                    <div class="product-inner">
                                                                                    <div class="stamp red">Sold</div>
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-23.jpg.pagespeed.ce.myNttexobP.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$576</h4>
                                            <h5 class="no-margin isotope--title">Sit Elit Vel</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--accessories" data-price="1090" data-popularity="4" data-size="s|xl" data-color="red|purple" data-brand="puma">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-24.jpg.pagespeed.ce.lEoWFT7nFI.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1090</h4>
                                            <h5 class="no-margin isotope--title">Est Condimentum Ut</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--vests" data-price="54" data-popularity="4" data-size="xs|s|l|xxl" data-color="blue|pink" data-brand="s-oliver">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-25.jpg.pagespeed.ce.xJJfKy1ctx.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$54</h4>
                                            <h5 class="no-margin isotope--title">Vel Adipiscing Est</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--trainers" data-price="1016" data-popularity="5" data-size="xs|s|m|xxl" data-color="red" data-brand="puma">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-26.jpg.pagespeed.ce.nQWAYlt5Ha.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1016</h4>
                                            <h5 class="no-margin isotope--title">Elit Vivamus Est Sit Condimentum</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--accessories" data-price="1280" data-popularity="3" data-size="m|l" data-color="red|orange" data-brand="nike">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-27.jpg.pagespeed.ce.uQO61sTD6h.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1280</h4>
                                            <h5 class="no-margin isotope--title">Sit Ac Duis Amet</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--blazers" data-price="1368" data-popularity="4" data-size="xs|l" data-color="blue|purple" data-brand="naish">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-28.jpg.pagespeed.ce.KafkrIYpz7.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1368</h4>
                                            <h5 class="no-margin isotope--title">Sit Felis</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--shorts" data-price="454" data-popularity="4" data-size="xs|s|l|xl" data-color="green|pink" data-brand="puma">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-29.jpg.pagespeed.ce.IIRdPIqso_.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$454</h4>
                                            <h5 class="no-margin isotope--title">Sit Neque Dapibus</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--bags" data-price="228" data-popularity="3" data-size="s|xl|xxl" data-color="blue" data-brand="shred">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-30.jpg.pagespeed.ce.7Sx6wEwaD0.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$228</h4>
                                            <h5 class="no-margin isotope--title">Ipsum Elit Neque Ac</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--bags" data-price="1045" data-popularity="5" data-size="s|m|l|xl" data-color="red" data-brand="puma">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-31.jpg.pagespeed.ce.qcxMmISnaf.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1045</h4>
                                            <h5 class="no-margin isotope--title">Lorem Vulputate</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--swimwear" data-price="1558" data-popularity="3" data-size="xs|s|l" data-color="pink|purple" data-brand="s-oliver">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/540x374xproduct-32.jpg.pagespeed.ic.cYj7H0BB4k.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1558</h4>
                                            <h5 class="no-margin isotope--title">Sit Consectetur Adipiscing Elit</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--shirts" data-price="3" data-popularity="5" data-size="xs|m" data-color="pink" data-brand="puma">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-33.jpg.pagespeed.ce.ScmDb1T3Wy.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$3</h4>
                                            <h5 class="no-margin isotope--title">Dolor Vivamus Metus</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--sunglasses" data-price="197" data-popularity="5" data-size="xs|s|xxl" data-color="blue" data-brand="s-oliver">
                                <div class="product">
                                    <div class="product-inner">
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-34.jpg.pagespeed.ce.qmvgXoakgS.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$197</h4>
                                            <h5 class="no-margin isotope--title">Sit Ac Duis</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                <span class="icon-star stars-clr"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                                                        <!--  ==========  -->
                            <!--  = Single Product =  -->
                            <!--  ==========  -->
                            <div class="span3 isotope--target filter--blazers" data-price="1120" data-popularity="1" data-size="s|xl|xxl" data-color="pink" data-brand="adidas">
                                <div class="product">
                                    <div class="product-inner">
                                                                                    <div class="stamp green">New</div>
                                                                                <div class="product-img">
                                            <div class="picture">
                                                <a href="product.html"><img width="540" height="374" alt="" src="images/dummy/products/product-35.jpg.pagespeed.ce.2_Bct1j-Do.jpg"/></a>
                                                <div class="img-overlay">
                                                    <a class="btn more btn-primary" href="product.html">More</a>
                                                    <a class="btn buy btn-danger" href="#">Add to Cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="main-titles no-margin">
                                            <h4 class="title">$1120</h4>
                                            <h5 class="no-margin isotope--title">Elit Vel Dapibus Amet Feugiat</h5>
                                        </div>
                                        <div class="row-fluid hidden-line">
                                            <div class="span6">
                                                <a href="#" class="btn btn-small"><i class="icon-heart"></i></a>
                                                <a href="#" class="btn btn-small"><i class="icon-exchange"></i></a>
                                            </div>
                                            <div class="span6 align-right">
                                                    <span class="icon-star stars-clr"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                <span class="icon-star"></span>
                                                                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- /single product -->
                            
                        </div>
                    </div>
                    <hr/>
                </section> <!-- /main content -->
            </div>
        </div>
    </div> <!-- /container -->