<?php echo $this->render('layout/bread.phtml')?>
        
        <div class="workplace">
			<div class="page-header">
                    <h1>Vị trí <small>tại các trang</small></h1>
            </div>
            <?php echo $this->render('layout/menuintro.phtml')?>
            <div class="alert alert-info">                
            Phục vụ cho Seo website của bạn lên các bộ máy tìm kiếm như Google, Yahoo, Bing, vv...
            </div>
            
            
            <div class="dr"><span></span></div>            
            
        </div>
       