

<!--  ==========  -->
    <!--  = Breadcrumbs =  -->
    <!--  ==========  -->
    <div class="darker-stripe">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li><span class="icon-chevron-right"></span></li>
                        <li>
                            <a href="">Blog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="push-up top-equal blocks-spacer">
            <div class="row">
                
                <!--  ==========  -->
                <!--  = Main Title =  -->
                <!--  ==========  -->
                
                <div class="span12">
                    <div class="title-area">
                        <h1 class="inline"><span class="light"><?php echo $result->title ?></span> Blog</h1>
                    </div>
                </div>
                
                <!--  ==========  -->
                <!--  = Main content =  -->
                <!--  ==========  -->
                <section class="span8 single single-post">
                    
                    <!--  ==========  -->
                    <!--  = Post =  -->
                    <!--  ==========  -->
                    <article class="post format-video">
                        <div class="post-inner">
                            <?php echo $result->description ?>                  
                        </div>
                    </article>
                    
                    <hr/>
                    
                    <!--  ==========  -->
                    <!--  = Comments =  -->
                    <!--  ==========  -->
                    <?php $uri = $this->serverUrl(true)  ?>
                    <section id="comments" class="comments-container">
                        <h3 class="push-down-25"><span class="light"><fb:comments-count href=<?php echo $uri ?>/></fb:comments-count></span> Bình luận</h3>
                        
                        
                        <hr/>
                        
                        <div class="fb-comments" data-width="100%" data-href="<?php echo $uri ?>" data-numposts="5" data-colorscheme="light"></div>
                        
                    </section>

                </section> <!-- /main content -->
                
                <!--  ==========  -->
                <!--  = Sidebar =  -->
                <!--  ==========  -->
                <?php include('include/sidebar.phtml') ?>
                <!-- /sidebar --> 

            </div>
        </div>
    </div> <!-- /container -->