<div class="row breadcrumb">
				<ul>
					<li><a href="/"><img src="<?php echo $this->basepath()?>/template/main/img/iconhome.png" style="vertical-align: top;"/> Trang chủ</a></li>
					<li><img src="<?php echo $this->basepath()?>/template/main/img/arrow.png" /></li>
					<li><a href=""><?php echo $title ?></a></li>
				</ul>
			</div><!-- End breadcrumb -->
		</header><!-- End header -->
<section class="content">
<div class="row">
				<div class="col-sm-2" style="padding-left:0">
					<div class="ads-left">
					<?php foreach ($block as $service): if($service['module'] == 2 && $service['position'] == 'ads_left'): ?>
							<?php echo $service['html'] ?>
							<style>
							<!--
							<?php echo $service['css'] ?>
							-->
							</style>
				        	<?php endif; endforeach;?>
					</div><!-- End ads-left -->
					
				</div>
				<div class="col-sm-8 news">
					<div class="row">
						<div class="col-sm-12">
							<h1 style="font-size: 20px; font-weight: bold">
							<?php if(@$_GET['lang'] == 'en') echo "Service" ; else echo "Dịch vụ" ?>
							</h1>
							<?php if(@$_GET['lang'] == 'en') echo $intro->description_en; else echo $intro->description ?>
								
						</div>
					</div>
					
					
					
				</div>
				<div class="col-sm-2">
							<div class="project">
								<?php include 'include/duan.phtml';?>
							</div><!-- End project -->
							<div class="ads2" style="margin-top: 10px">
							<?php foreach ($block as $service): if($service['module'] == 2 && $service['position'] == 'ads_right'): ?>
							<?php echo $service['html'] ?>
							<style>
							<!--
							<?php echo $service['css'] ?>
							-->
							</style>
				        	<?php endif; endforeach;?></div><!-- End ads2 -->
				</div>
			</div>