<script type="text/javascript">

function BrowseServer( startupPath, functionData )
{
	// You can use the "CKFinder" class to render CKFinder in a page:
	var finder = new CKFinder();

	// The path for the installation of CKFinder (default = "/ckfinder/").
	finder.basePath = '../';

	//Startup path in a form: "Type:/path/to/directory/"
	finder.startupPath = startupPath;

	// Name of a function which is called when a file is selected in CKFinder.
	finder.selectActionFunction = SetFileField;

	// Additional data to be passed to the selectActionFunction in a second argument.
	// We'll use this feature to pass the Id of a field that will be updated.
	finder.selectActionData = functionData;

	// Name of a function which is called when a thumbnail is selected in CKFinder.
	finder.selectActionFunction = ShowThumbnails;

	// Launch CKFinder
	finder.popup();
}

// This is a sample function which is called when a file is selected in CKFinder.
function SetFileField( fileUrl, data )
{
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

// This is a sample function which is called when a thumbnail is selected in CKFinder.
function ShowThumbnails( fileUrl, data )
{

	// this = CKFinderAPI
	var sFileName = this.getSelectedFile().name;
	document.getElementById('thumbnails').innerHTML = '';
	document.getElementById('thumbnails').innerHTML +=
			
			'<div class="thumb">' +
				'<img src="' + fileUrl + '" />' +
				'<div class="caption">' +
					'<a href="' + data["fileUrl"] + '" target="_blank">' + sFileName + '</a> (' + data["fileSize"] + 'KB)' +
				'</div>' +
			'</div>';

	
	// It is not required to return any value.
	// When false is returned, CKFinder will not close automatically.
	document.getElementById( data["selectActionData"] ).value = fileUrl;
	return true;
}

</script>
<script type="text/javascript">
				$(document).ready(function(){
					$("#validation").submit(function(){
					    parent.closeModal();
					});
				})
			</script>

<div class="row-fluid">
               	<?php
				$form = $this->form;
				$form->setAttributes ( array (
				'id' => 'validation') );
				$form->setAttribute ( 'action', $this->url ( 'tintuc', array (
				'action' => 'edit','id'=>$this->id ) ) );
				$form->prepare ();
				echo $this->form ()->openTag ( $form );
				?>
                <div class="span12">
              	<?php echo $this->formhidden($form->get('id')); ?>
                <?php echo $this->formhidden($form->get('date'))?> 
                <?php echo $this->formhidden($form->get('title'))?>
                
                    <div class="block-fluid tabs">
                        
                        <ul>
                            <li><a href="#tabs-1">Thông tin cơ bản</a></li>
                            <li><a href="#tabs-2">Nội dung</a></li>
                            <li><a href="#tabs-3">SEO</a></li>
                        </ul>                        
                        
                                                
                        
                        <div id="tabs-1">
                            <div class="block-fluid">                        
								
									
								<div class="row-form">
									<div class="span2">Tiêu đề ( Tiếng Việt ) :</div>
									<div class="span3"><?php echo $this->forminput($form->get('title'))?></div>
									
									<div class="span2 offset1">Đường dẫn tối ưu (*) :</div>
									<div class="span3"><?php echo $this->forminput($form->get('alias'))?> <span>Example: dien-thoai</span></div>
									<div class="clear"></div>
								</div>
								
								<div class="row-form">
									<div class="span2">Tiêu đề ( Tiếng Anh ) :</div>
									<div class="span3"><?php echo $this->forminput($form->get('title_en'))?></div>
									<div class="clear"></div>
								</div>
								
								<div class="row-form">
									<div class="span2">Bài viết nổi bật :</div>
									<div class="span3">
									<?php echo $this->formcheckbox($form->get('index'))?>
									</div>
									<div class="span2 offset1">Thể loại :</div>
									<div class="span3">
										<?php echo $this->formselect($form->get('category'))?>
	
									</div>
									<div class="clear"></div>
								</div>
								
								<div class="row-form">
									<div class="span2">Nguồn tin :</div>
									<div class="span3"><?php echo $this->forminput($form->get('resources'))?></div>
									<div class="span2 offset1">Người soạn  :</div>
									<div class="span3">
										<?php echo $this->forminput($form->get('author'))?>
									</div>
									<div class="clear"></div>
								</div>
								<div class="row-form">
									<div class="span2">Lượt xem :</div>
									<div class="span3"><?php echo $this->forminput($form->get('view'))?></div>
									<div class="span2 offset1">Tag  :</div>
									<div class="span3">
										<?php echo $this->forminput($form->get('tag'))?>
									</div>
									<div class="clear"></div>
								</div>
								<div class="row-form">
									<div class="span2">Ảnh đại diện :</div>
									<div class="span3">
									<div class="widgetButtons" style="text-align: left">                        
							   
										<div class="bb" id="thumbnails">
										<img src="<?php echo $form->image ?> />
										<span class="ibw-plus"></span>
										</div>
									</div>
									<?php echo $this->forminput($form->get('image'))?>
									<input type="button" value="Chọn ảnh"
									onclick="BrowseServer( 'Images:/', 'xImagePath' );" />
									</div>
									<div class="span2 offset1">Trạng thái  :</div>
									<div class="span3">
										<?php echo $this->formselect($form->get('active'))?>
									</div>
									<div class="clear"></div>
								</div>
				
							</div>
                        </div>
						
						
                                                
                        <div id="tabs-2">
                            <div class="block">
								<div class="row-form">
								<div class="span12">
									<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Mô tả ngắn</h4>
									<?php echo $this->formtextarea($form->get('summary'))?>
									
									
								</div>
								<div class="clear"></div>
								</div>
								<div class="row-form">
								<div class="span12">
									<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Mô tả ngắn ( Tiếng Anh )</h4>
									<?php echo $this->formtextarea($form->get('summary_en'))?>
								</div>
								<div class="clear"></div>
								</div>
								<div class="row-form">
								<div class="span12">
									<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Mô tả</h4>
									<?php echo $this->formtextarea($form->get('description'))?>
									
								</div>
								<div class="clear"></div>
								</div>
								<div class="row-form">
								<div class="span12">
									<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Mô tả ( Tiếng Anh )</h4>
								
									<?php echo $this->formtextarea($form->get('description_en'))?>
								</div>
								<div class="clear"></div>
								</div>
							</div>
                        </div>
						
						
						<div id="tabs-3">
                            <div class="block">
						
							<div class="row-form">
							
							<div class="span12"><h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Mô tả nội dung </h4>
								<?php echo $this->formtextarea($form->get('meta'))?>
							</div>
							<div class="clear"></div>
							</div>
							<div class="row-form">
							<div class="span12">
							<h4 style="font-family: Cambria, Georgia, serif; font-style: italic"> Từ khóa </h4>
							<?php echo $this->forminput($form->get('keyword'))?> <span>
							
							</div>
							<div class="clear"></div>
							</div>
							
							</div>
                        </div>
						<div class="footer tar">
                                <button class="btn"> Thêm tin tức </button>
								</div>	
                        
                    </div>
                </div>                                
                </form>
            </div> 
            