<div class="row breadcrumb">
				<ul>
					<li><a href="/"><img src="<?php echo $this->basepath()?>/template/main/img/iconhome.png" style="vertical-align: top;"/> Trang chủ</a></li>
					<li><img src="<?php echo $this->basepath()?>/template/main/img/arrow.png" /></li>
					<li><a href=""><?php echo $title ?></a></li>
				</ul>
			</div><!-- End breadcrumb -->
		</header><!-- End header -->
<section class="content">
<div class="row">
				<div class="col-sm-2" style="padding-left:0">
					<div class="ads-left">
					<?php foreach ($block as $service): if($service['module'] == 2 && $service['position'] == 'ads_left'): ?>
					<?php echo $service['html'] ?>
					<style>
					<!--
					<?php echo $service['css'] ?>
					-->
					</style>
		        	<?php endif; endforeach;?>
					</div><!-- End ads-left -->
					<div class="new-old">
						<div class="title"><?php if(@$_GET['lang'] == 'en') echo "Older posts" ; else echo "Những tin cũ" ?></div>
							<div class="item">
								<ul>
								<?php foreach ($tincu as $tincus):?>
									<li><a href="<?php echo $this->url('chitiettintuc', array('alias'=>$tincus->alias))?><?php if(@$_GET['lang'] == 'en') echo "?lang=en"?>"><?php if(@$_GET['lang'] == 'en') echo $tincus->title_en ; else echo $tincus->title ?></a></li>
								<?php endforeach;?>
								</ul>
							</div>
					</div><!-- End new-old -->
				</div>
				<div class="col-sm-8 news">
					<div class="row">
						<div class="col-sm-12">
							<h1 style="font-size: 20px; font-weight: bold"><?php if(@$_GET['lang'] == 'en') echo "News" ; else echo "Tin tức" ?></h1>
							<?php if(@$_GET['lang'] == 'en') echo $intro->summary_en ; else echo $intro->summary ?>
								
						</div>
					</div>
					<div class="row">
						<div class="col-sm-8">
						<?php $i=0; foreach ($catenew as $catenews):?>
							<div class="title"><?php if(@$_GET['lang'] == 'en') echo $catenews['name_en'] ; else echo $catenews['name'] ?></div>
							<div class="item-list">
							<?php  foreach ($tincate[$i] as $tincates):?>
							
								<div class="media">
								  <a class="pull-left" href="#">
									<img class="media-object" src="<?php echo $tincates->image ?>" alt="<?php echo $tincates->title ?>">
								  </a>
								  <div class="media-body1">
									<h5 class="media-heading"><a href="<?php echo $this->url('chitiettintuc', array('alias'=>$tincates->alias))?><?php if(@$_GET['lang'] == 'en') echo "?lang=en"?>">
									<?php if(@$_GET['lang'] == 'en') echo $tincates->title_en ; else echo $tincates->title ?></a></h5>
									<p>
									<?php if(@$_GET['lang'] == 'en') echo $tincates->summary_en ; else echo $tincates->summary ?>
									</p>
								  </div>
								</div>
							<?php  endforeach;?>
							
								
							</div><!-- End item-list -->
						<?php $i++; endforeach;?>
							
						</div>
						<div class="col-sm-4">
							<div class="new-hot">
								<div class="title" style="border-bottom: 1px solid #fff"><?php if(@$_GET['lang'] == 'en') echo "News Hot" ; else echo "Tin nóng" ?></div>
								<ul>
								<?php foreach ($tinnong as $tinnongs):?>
									<li><a href="<?php echo $this->url('chitiettintuc', array('alias'=>$tinnongs->alias))?><?php if(@$_GET['lang'] == 'en') echo "?lang=en"?>"><?php if(@$_GET['lang'] == 'en') echo $tinnongs->title_en ; else echo $tinnongs->title ?></a></li>
								<?php endforeach;?>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-2">
							<div class="project">
								<?php include 'include/duan.phtml';?>
							</div><!-- End project -->
							<div class="ads2" style="margin-top: 10px">
							<?php foreach ($block as $service): if($service['module'] == 2 && $service['position'] == 'ads_right'): ?>
							<?php echo $service['html'] ?>
							<style>
							<!--
							<?php echo $service['css'] ?>
							-->
							</style>
				        	<?php endif; endforeach;?>
							</div><!-- End ads2 -->
				</div>
			</div>