
			
<!DOCTYPE html>
<!--[if lt IE 8]>      <html class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  
<!-- Mirrored from www.proteusthemes.com/themes/webmarket-html/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 18 Oct 2014 05:30:48 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(); ?>
		<!-- Display Meta Keywords and Description along with Viewport -->
		<?php echo $this->headMeta()->appendName('viewport', 
		        'width=device-width, initial-scale=1.0') ?>
	
		<?php echo $this->headScript(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!--  = Google Fonts =  -->
    <script type="text/javascript">WebFontConfig={google:{families:['Open+Sans:400,700,400italic,700italic:latin,latin-ext,cyrillic','Pacifico::latin']}};(function(){var wf=document.createElement('script');wf.src=('https:'==document.location.protocol?'https':'http')+'://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';wf.type='text/javascript';wf.async='true';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(wf,s);})();</script>

    <!-- Twitter Bootstrap -->
    <link href="<?php echo $this->basepath()?>/template/main/main.css" rel="stylesheet"/>
    
    <!-- Slider Revolution -->
    
    <!-- jQuery UI -->
    
    <!-- PrettyPhoto -->
    
    <!-- main styles -->
        
    

    <!-- Modernizr -->
    <script src="<?php echo $this->basepath()?>/template/main/js/modernizr.custom.56918.js.pagespeed.jm.uJEwd3FIaL.js"></script>

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->basepath()?>/template/main/images/apple-touch/144.png.pagespeed.ce.HQhWeqIdDJ.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->basepath()?>/template/main/images/apple-touch/114.png.pagespeed.ce.3cV3NB-LbK.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->basepath()?>/template/main/images/apple-touch/72.png.pagespeed.ce.Yg3RzDogzO.png">
    <link rel="apple-touch-icon-precomposed" href="<?php echo $this->basepath()?>/template/main/images/apple-touch/57.png.pagespeed.ce.nx1OijlsPq.png">
    <link rel="shortcut icon" href="<?php echo $this->basepath()?>/template/main/images/apple-touch/57.png.pagespeed.ce.nx1OijlsPq.png">
    <div id="fb-root"></div>
    <script>(function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));</script>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-531a7f980744a2e5" async="async"></script>
    <script type="text/javascript">
        window.fbAsyncInit = function() {
            FB.init({
              appId      : '552475738218386',
              xfbml      : true,
              version    : 'v2.1'
            });
            FB.XFBML.parse();
          };
    </script>
  </head>

    <body class="">

    <div class="master-wrapper">
        <!--  ==========  -->
    <!--  = Header =  -->
    <!--  ==========  -->
    <header id="header">
        <div class="darker-row">
            <div class="container">
                <div class="row">
                    <div class="span4">
                        <div class="higher-line">
                            Welcome to website Vnref
                        </div>
                    </div>
                    <div class="span8">
                        <div class="topmost-line">
                            <div class="higher-line">
                                <a href="/" class="gray-link">Home</a>
                            </div>&nbsp;
                            <div class="higher-line">
                                <a href="" class="gray-link">News</a>
                            </div>&nbsp;
                            <div class="higher-line">
                                <a href="" class="gray-link">About</a>
                            </div>&nbsp;
                            <div class="higher-line">
                                <a href="<?php echo $this->url('lienhe') ?>" class="gray-link">Contact</a>
                            </div>&nbsp;
                            <div class="higher-line">
                                <a href="" class="gray-link">Cart</a>
                            </div>
                            &nbsp;
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">

                <!--  ==========  -->
                <!--  = Logo =  -->
                <!--  ==========  -->
                <div class="span7">
                    <a class="brand" href="/">
                        <img src="<?php echo $this->basepath()?>/template/main/images/logo.png.pagespeed.ce.zVDKa4LAZz.png" alt="Webmarket Logo" width="48" height="48"/>
                        <span class="pacifico">Vnref Online</span>
                        <span class="tagline">Really Cool e-Commerce</span>
                    </a>
                </div>

                <!--  ==========  -->
                <!--  = Social Icons =  -->
                <!--  ==========  -->
                <div class="span5">
                    <div class="top-right">
                        <div class="icons">
                            <a href=""><span class="zocial-facebook"></span></a>
                            <a href=""><span class="zocial-skype"></span></a>
                            <a href=""><span class="zocial-twitter"></span></a>
                            <a href=""><span class="zocial-rss"></span></a>
                            <a href="#"><span class="zocial-wordpress"></span></a>
                            <a href="#"><span class="zocial-android"></span></a>
                            <a href="#"><span class="zocial-html5"></span></a>
                            <a href="#"><span class="zocial-windows"></span></a>
                            <a href="#"><span class="zocial-apple"></span></a>
                        </div>
                    </div>
                </div> <!-- /social icons -->
            </div>
        </div>
    </header>

    <!--  ==========  -->
    <!--  = Main Menu / navbar =  -->
    <!--  ==========  -->
    <div class="navbar navbar-static-top" id="stickyNavbar">
      <div class="navbar-inner">
        <div class="container">
          <div class="row">
            <div class="span9">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>

                <!--  ==========  -->
                <!--  = Menu =  -->
                <!--  ==========  -->
                <div class="nav-collapse collapse">
                  <ul class="nav" id="mainNavigation">
                   <?php $catepro = $this->catepro() ?>
                   <?php foreach($catepro as $catepros): ?>
                    <li class="active"><a href="<?php echo $this->url('categoryProduct', array('alias'=>$catepros['alias'])) ?>"><?php echo $catepros['name'] ?></a></li>
                   <?php endforeach ?>
                  </ul>

                  <!--  ==========  -->
                  <!--  = Search form =  -->
                  <!--  ==========  -->
                  <form class="navbar-form pull-right" action="#" method="get">
                      <button type="submit"><span class="icon-search"></span></button>
                      <input type="text" class="span1" name="search" id="navSearchInput">
                  </form>
                </div><!-- /.nav-collapse -->
            </div>

            <!--  ==========  -->
            <!--  = Cart =  -->
            <!--  ==========  -->
            <div class="span3">
                <div class="cart-container" id="cartContainer">
                    <div class="cart">
                        <p class="items">CART <span class="dark-clr">(3)</span></p>
                        <p class="dark-clr hidden-tablet">1816.90đ</p>
                        <a href="checkout-step-1.html" class="btn btn-danger">
                            <!-- <span class="icon icons-cart"></span> -->
                            <i class="icon-shopping-cart"></i>
                        </a>
                    </div>
                    <div class="open-panel">
                                                <div class="item-in-cart clearfix">
                            <div class="image">
                                <img src="<?php echo $this->basepath()?>/template/main/images/dummy/cart-items/124x124xcart-item-1.jpg.pagespeed.ic.MOH6pViKb3.jpg" width="124" height="124" alt="cart item"/>
                            </div>
                            <div class="desc">
                                <strong><a href="product.html">Sit Consectetur Vel Nisi Eros Amet</a></strong>
                                <span class="light-clr qty">
                                    Qty: 1
                                    &nbsp;
                                    <a href="#" class="icon-remove-sign" title="Remove Item"></a>
                                </span>
                            </div>
                            <div class="price">
                                <strong>$3264</strong>
                            </div>
                        </div>
                                                <div class="item-in-cart clearfix">
                            <div class="image">
                                <img src="<?php echo $this->basepath()?>/template/main/images/dummy/cart-items/124x124xcart-item-2.jpg.pagespeed.ic.pWDTtNZ7M8.jpg" width="124" height="124" alt="cart item"/>
                            </div>
                            <div class="desc">
                                <strong><a href="product.html">Ipsum Consectetur Adipiscing Ac Metus</a></strong>
                                <span class="light-clr qty">
                                    Qty: 1
                                    &nbsp;
                                    <a href="#" class="icon-remove-sign" title="Remove Item"></a>
                                </span>
                            </div>
                            <div class="price">
                                <strong>$5922</strong>
                            </div>
                        </div>
                                                <div class="item-in-cart clearfix">
                            <div class="image">
                                <img src="<?php echo $this->basepath()?>/template/main/images/dummy/cart-items/124x124xcart-item-3.jpg.pagespeed.ic.SxHNASdP7z.jpg" width="124" height="124" alt="cart item"/>
                            </div>
                            <div class="desc">
                                <strong><a href="product.html">Vivamus Tincidunt Est Condimentum</a></strong>
                                <span class="light-clr qty">
                                    Qty: 1
                                    &nbsp;
                                    <a href="#" class="icon-remove-sign" title="Remove Item"></a>
                                </span>
                            </div>
                            <div class="price">
                                <strong>$3865</strong>
                            </div>
                        </div>
                                                <div class="summary">
                            <div class="line">
                                <div class="row-fluid">
                                    <div class="span6">Shipping:</div>
                                    <div class="span6 align-right">$4.99</div>
                                </div>
                            </div>
                            <div class="line">
                                <div class="row-fluid">
                                    <div class="span6">Subtotal:</div>
                                    <div class="span6 align-right size-16">$357.81</div>
                                </div>
                            </div>
                        </div>
                        <div class="proceed">
                            <a href="checkout-step-1.html" class="btn btn-danger pull-right bold higher">CHECKOUT <i class="icon-shopping-cart"></i></a>
                            <small>Shipping costs are calculated based on location. <a href="#">More information</a></small>
                        </div>
                    </div>
                </div>
            </div> <!-- /cart -->
          </div>
        </div>
      </div>
    </div> <!-- /main menu -->