<!DOCTYPE html>
<html lang="en">
<head>        
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

    <title>Login - Aquarius - responsive admin panel</title>

    <link rel="icon" type="image/ico" href="favicon.ico"/>
    
    <link href="<?php echo $this->basepath()?>/template/admin/css/stylesheets.css" rel="stylesheet" type="text/css" />
    <link rel='stylesheet' type='text/css' href='<?php echo $this->basepath()?>/template/admin/css/fullcalendar.print.css' media='print' />
    
    <script type='text/javascript' src='../../../ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js'></script>
    <script type='text/javascript' src='../../../ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js'></script>
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/jquery/jquery.mousewheel.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/cookie/jquery.cookies.2.2.0.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/bootstrap.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/charts/excanvas.min.js'></script>
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/charts/jquery.flot.js'></script>    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/charts/jquery.flot.stack.js'></script>    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/charts/jquery.flot.pie.js'></script>
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/charts/jquery.flot.resize.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/sparklines/jquery.sparkline.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/fullcalendar/fullcalendar.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/select2/select2.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/uniform/uniform.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/maskedinput/jquery.maskedinput-1.3.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/validation/languages/jquery.validationEngine-en.js' charset='utf-8'></script>
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/validation/jquery.validationEngine.js' charset='utf-8'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js'></script>
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/animatedprogressbar/animated_progressbar.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/qtip/jquery.qtip-1.0.0-rc3.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/cleditor/jquery.cleditor.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/dataTables/jquery.dataTables.min.js'></script>    
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins/fancybox/jquery.fancybox.pack.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/cookies.js'></script>
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/actions.js'></script>
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/charts.js'></script>
    <script type='text/javascript' src='<?php echo $this->basepath()?>/template/admin/js/plugins.js'></script>
    
</head>
<body>
    
   <?php echo $this->content ?>   
    
</body>
</html>
