<div class="row-fluid">
                    <div class="span12">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <div class="container">
                                   
                                   
                                    <div class="nav-collapse collapse navbar-responsive-collapse">
                                        <ul class="nav">
											<li class=""><a href="<?php echo $this->url('block',array('action'=>'list'))?>">Block hệ thống</a></li>
                                            <li class=""><a href="<?php echo $this->url('block',array('action'=>'html'))?>">Block HTML</a></li>
                                         
                                        </ul>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>    
                    </div>
                </div>