<div class="row-fluid">
                    <div class="span12">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <div class="container">
                                   
                                   
                                    <div class="nav-collapse collapse navbar-responsive-collapse">
                                        <ul class="nav">
											<li class=""><a href="<?php echo $this->url('tintuc',array('action'=>'list'))?>" id="taomenu">Quản lý tin tức</a></li>
                                            <li class=""><a href="<?php echo $this->url('theloaitin',array('action'=>'list'))?>">Thể loại</a></li>
                                         
                                        </ul>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>    
                    </div>
                </div>