<div class="row-fluid">
                    <div class="span12">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <div class="container">
                                   
                                   
                                    <div class="nav-collapse collapse navbar-responsive-collapse">
                                        <ul class="nav">
											<li class=""><a href="">Ý kiến khách hàng</a></li>
                                            <li class=""><a href="">Hỏi đáp</a></li>
                                         	<li class="<?php echo $this->url('lienhe', array('action'=>'list'))?>"><a href="">Danh sách liên hệ</a></li>
                                        </ul>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>    
                    </div>
                </div>