<div class="row-fluid">
	<div class="span12">
		<div class="navbar">
			<div class="navbar-inner">
				<div class="container">

					<div class="nav-collapse collapse navbar-responsive-collapse">

						<ul class="nav navbar-nav">
							<li class=""><a href="<?php echo $this->url('sanpham',array('action'=>'add'))?>">Đăng sản phẩm</a></li>
							<li><a href="<?php echo $this->url('sanpham',array('action'=>'list'))?>">Quản lý
									sản phẩm</a></li>
							<li><a href="<?php echo $this->url('danhmucsanpham',array('action'=>'list'))?>">Quản lý danh mục</a></li>
							<li><a href="<?php echo $this->url('thongtinlienhe',array('action'=>'list'))?>">Thông tin liên hệ</a>
							</li>
							<li><a href="<?php echo $this->url('thanhtoan',array('action'=>'list'))?>">Cài đặt thanh toán</a>
							</li>
							<li><a href="<?php echo $this->url('donhang',array('action'=>'list'))?>">Quản lý đơn hàng</a></li>
							<li><a href="<?php echo $this->url('thongso',array('action'=>'list'))?>">Thông số sản phẩm</a></li>
						</ul>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>