<div class="row-fluid">
                    <div class="span12">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <div class="container">
                                   
                                   
                                    <div class="nav-collapse collapse navbar-responsive-collapse">
                                        <ul class="nav">
											<li class=""><a href="javascript::void()" id="taomenu">Tạo menu</a></li>
                                            <li class=""><a href="#">Menu</a></li>
                                            <li><a href="#">Menu items</a></li>
                                        </ul>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>    
                    </div>
                </div>