<div class="row-fluid">
                    <div class="span12">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <div class="container">
                                   
                                   
                                    <div class="nav-collapse collapse navbar-responsive-collapse">
                                        <ul class="nav">
											<li class=""><a href="<?php echo $this->url('intro',array('action'=>'basic'))?>" >Thông tin cơ bản</a></li>
                                            <li class=""><a href="<?php echo $this->url('intro',array('action'=>'seo'))?>">Tối ưu hóa tìm kiếm</a></li>
                                        	<li class=""><a href="<?php echo $this->url('intro',array('action'=>'googlewebmaster'))?>">Google wemaster</a></li>
                                        	<li class=""><a href="<?php echo $this->url('intro',array('action'=>'googlewebmaster'))?>">Tên miền riêng</a></li>
                                        	<li class=""><a href="<?php echo $this->url('intro',array('action'=>'googlewebmaster'))?>">Bản đồ</a></li>
                                        	<li class=""><a href="<?php echo $this->url('intro',array('action'=>'googlewebmaster'))?>">Chân trang</a></li>
                                        </ul>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>    
                    </div>
                </div>