<td id="column_right" style="width:240px">
		
					<div style="width:240px;">
												<!--// bof: bestsellers //-->
        <div class="box" id="bestsellers" style="width:240px;">


										
											<div class="box-head">
												Bestsellers											</div>
			
											<div class="box-body">
												<div id="bestsellersContent" class="sideBoxContent">
<div class="wrapper">
<ol>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=product_info&amp;products_id=27">John W. Nordstrom Wool Blend Suit</a></li>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=product_info&amp;products_id=1">Armani Collezioni Black Wool Suit</a></li>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=product_info&amp;products_id=21">HUGO Eneor Slim Fit Shirt</a></li>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=product_info&amp;products_id=26">John W. Nordstrom Wool Blend Suit</a></li>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=product_info&amp;products_id=13">Canali Tan Pinstripe Wool Suit</a></li>
</ol>
</div>
</div>											</div> 
			

            
        </div>
<!--// eof: bestsellers //-->

<!--// bof: information //-->
        <div class="box" id="information" style="width:240px;">


										
											<div class="box-head">
												Information											</div>
			
											<div class="box-body">
												<div id="informationContent" class="sideBoxContent">
<ul style="margin: 0; padding: 0; list-style-type: none;">
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=shippinginfo">Shipping &amp; Returns</a></li>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=privacy">Privacy Notice</a></li>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=conditions">Conditions of Use</a></li>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=contact_us">Contact Us</a></li>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=site_map">Site Map</a></li>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=gv_faq">Gift Certificate FAQ</a></li>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=discount_coupon">Discount Coupons</a></li>
<li><a href="http://livedemo00.template-help.com/zencart_45555/index.php?main_page=unsubscribe">Newsletter Unsubscribe</a></li>
</ul>
</div>											</div> 
			

            
        </div>
<!--// eof: information //-->

					</div>
		
				</td>