
<script type="text/javascript">
				$(document).ready(function(){
					$("#validation").submit(function(){
					    parent.closeModal();
					});
				})
			</script>

<div class="row-fluid">
                <form id="validation" method="POST" action="">
					<div class="span12">                    
                    
                    <div class="block-fluid">
							<div class="row-form">
								<div class="span5"><h4 style="font-family: Cambria, Georgia, serif; "> Thông tin đặt hàng </h4></div>
								
								<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span2">Mã hóa đơn :</div>
								<div class="span3"> 123</div>
								<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span2">Mã khách hàng :</div>
								<div class="span3"> 123</div>
								<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span2">Tên khách hàng :</div>
								<div class="span3"> Nguyễn Duy Nghĩa</div>
								<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span2">Địa chỉ giao hàng :</div>
								<div class="span3"> 123</div>
								<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span2">Số điện thoại :</div>
								<div class="span3"> 123</div>
								<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span2">Email :</div>
								<div class="span3"> 123</div>
								<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span2">Hình thức thanh toán :</div>
								<div class="span3"> 123</div>
								<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span2">Ghi chú :</div>
								<div class="span5"> 123</div>
								<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span5"><h4 style="font-family: Cambria, Georgia, serif; "> Sản phẩm 2/05/2014 17:05:24 </h4></div>
								
								<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span12">
									<table width="100%" cellpadding="5px" border="1px" bordercolor="#ccc" cellspacing="0">
										<tbody>
											<tr>
												<td>Mã SP</td>
												<td>Hình ảnh</td>
												<td>Tên sản phẩm</td>
												<td>Số lượng</td>
												<td>Đơn giá</td>
												<td>Thành tiền</td>
											</tr>
												<tr><td>ATN-108</td>
												<td><img src="1.jpg" width="100" height="100"/></td>
												<td>Áo thun cá sấu đủ màu sắc</td>
												<td>1</td>
												<td align="right">200.000</td>
												<td align="right">200.000</td>
											</tr>
												<tr>
												<td colspan="3">&nbsp;</td>
												<td colspan="2" align="right">Trị giá hóa đơn</td>
												<td align="right">200,000</td>
											</tr>
										</tbody>
									</table>
								</div>
								
								<div class="clear"></div>
							</div>
							<div class="row-form">
								<div class="span2"><h4 style="font-family: Cambria, Georgia, serif; "> Trạng thái </h4></div>
								<div class="span5">
										<select name="active" id="active" id="active">
											<option value="">Chọn tình trạng</option>
											<option value="0">Chưa xử lý</option>
											<option value="1">Hủy</option>
											<option value="2">Đã giao hàng</option>
										</select>
								</div>
								<div class="clear"></div>
							</div>
							<div class="footer tar">
                                <button class="btn"> Cập nhập </button>
							</div>	
                    </div>
                </div>							
                </form>
            </div>