<?php echo $this->render('layout/bread.phtml')?>
        
        <div class="workplace">
			<div class="page-header">
                    <h1>Quản lý <small>thông tin liên hệ</small></h1>
            </div>
            <?php echo $this->render('layout/menusanpham.phtml')?>
            
            <div class="row-fluid">
                <?php
				$form = $this->form;
				$form->setAttributes ( array (
				'id' => 'validation' ) );
				$form->setAttribute ( 'action', $this->url ( 'thongtinlienhe', array (
				'action' => 'list' ) ) );
				$form->prepare ();
				echo $this->form ()->openTag ( $form );
				?>
                <div class="span12">   
                <input type="hidden" name="id" />                 
                    <div class="head">
                        <div class="isw-list"></div>
                        <h1>Thông tin liên hệ</h1>
						<ul class="buttons">
                                <li><a href="#" class="isw-ok"></a></li>
                                
                            </ul>
                        <div class="clear"></div>
                    </div>
                    <div class="block-fluid">
						<div class="row-form">
										<div class="span2">Tên liên hệ chọn đăng SP :</div>
										<div class="span3"><?php echo $this->forminput($form->get('namecontact'))?><span> Tên khi chọn đăng trong phần đăng sản phẩm  </span></div>
										<div class="span2 offset1">Tên người liên hệ :</div>
										<div class="span3">
											<?php echo $this->forminput($form->get('contactperson'))?>

										<span>Tên của người liên hệ đại lý nào đó ?</span></div>
										<div class="clear"></div>
							</div>
							<div class="row-form">
										<div class="span2">Tên doanh nghiệp :</div>
										<div class="span3"><?php echo $this->forminput($form->get('business'))?></div>
										<div class="span2 offset1">Địa chỉ :</div>
										<div class="span3">
											<?php echo $this->forminput($form->get('address'))?>
										</div>
										<div class="clear"></div>
							</div>
							<div class="row-form">
										<div class="span2">Giấy phép kinh doanh :</div>
										<div class="span3"><?php echo $this->forminput($form->get('license'))?></div>
										<div class="span2 offset1">Mã số thuế :</div>
										<div class="span3">
											<?php echo $this->forminput($form->get('taxcode'))?>
										</div>
										<div class="clear"></div>
							</div>
							<div class="row-form">
										<div class="span2">Điện thoại :</div>
										<div class="span3"><?php echo $this->forminput($form->get('phone'))?></div>
										<div class="span2 offset1">Email :</div>
										<div class="span3">
											<?php echo $this->forminput($form->get('email'))?>
										</div>
										<div class="clear"></div>
							</div>
							<div class="row-form">
										<div class="span2">Yahoo :</div>
										<div class="span3"><?php echo $this->forminput($form->get('yahoo'))?></div>
										<div class="span2 offset1">Skype :</div>
										<div class="span3">
											<?php echo $this->forminput($form->get('skype'))?>
										</div>
										<div class="clear"></div>
							</div>
							<div class="footer tar">
                                <button class="btn"> Thêm danh mục </button>
							</div>	
                    </div>
                </div>                                
                </form>
            </div> 
            <div class="row-fluid">
                
                <div class="span12">                    
                    <div class="head">
                        <div class="isw-grid"></div>
                        <h1>Danh sách</h1>
						<ul class="buttons">
                            <li><a href="#" class="isw-download"></a></li>                                                        
                            <li><a href="#" class="isw-attachment"></a></li>
                            <li>
                                <a href="#" class="isw-settings"></a>
                                <ul class="dd-list">
                                    <li><a href="#"><span class="isw-plus"></span> New document</a></li>
                                    <li><a href="#"><span class="isw-edit"></span> Edit</a></li>
                                    <li><a href="#"><span class="isw-delete"></span> Delete</a></li>
                                </ul>
                            </li>
                        </ul>               
                        <div class="clear"></div>
                    </div>
					
                    <div class="block-fluid table-sorting">
                        <table cellpadding="0" cellspacing="0" width="100%" class="table" id="tSortable">
                            <thead>
                                <tr>
                                    <th width="5%"><input type="checkbox" name="checkall"/></th>
                                    <th width="5%">STT</th>
									<th width="10%">Tên liên hệ</th>
									<th width="15%">Tên người liên hệ</th>
									<th width="15%">Địa chỉ</th>
                                    <th width="15%">Điện thoại</th>
									<th width="15%">Email</th>
                                    <th width="10%">Skype</th>
									<th width="10%">Hành động</th>                                    
                                </tr>
                            </thead>
                            <tbody class="category">
                            <?php foreach ($Thongtinlienhe as $Thongtinlienhes):?>
                                <tr>
                                    <td><input type="checkbox" name="checkbox"/></td>
                                    <td><?php echo $Thongtinlienhes->id?></td>
                                    <td><?php echo $Thongtinlienhes->namecontact ?></td>
                                    <td><?php echo $Thongtinlienhes->contactperson ?></td>
                                    <td><?php echo $Thongtinlienhes->address ?></td>
									<td><?php echo $Thongtinlienhes->phone ?></td>
                                    <td><?php echo $Thongtinlienhes->email ?></td>
                                    <td><?php echo $Thongtinlienhes->skype ?></td>
                                    <td class="action_hanhdong">
										<a href="javascript::void()" title="Sửa" data-href="<?php echo $this->url('thongtinlienhe',array('action'=>'edit','id'=>$Thongtinlienhes->id))?>" id="dialogBtn"><i class="fa fa-pencil-square-o"></i></a>
										<a data-href="<?php echo $this->url('thongtinlienhe', array('action'=>'delete','id'=>$Thongtinlienhes->id))?>" href="javascript::void()" class="delete"><i class="fa fa-trash-o" title="Xóa"></i></a>
									</td>
                                    
                                </tr>
                             <?php endforeach;?>
                                       
                            </tbody>
                        </table>
                        <div class="clear"></div>
                    </div>
                </div>                                
                
            </div>            
            
            <div class="dr"><span></span></div>            
            
        </div>
        <script type='text/javascript'>
		$(document).ready(function(){
			$("#dialog").dialog({
				autoOpen: false,
				modal: true,
				height: 600,
				width: 960,
				show: 'blind',
				
				 
			});

			
			$('body').on('click','a#dialogBtn', function(){
				var ahref = $(this).attr('data-href');
				$('#dialog').dialog('open');
				$('#myIframe').attr('src', ahref);
				
			})
			
			$('body').on('click','a.delete', function()
			{
				var r = confirm("Nếu xóa thì các liên kết đến thông tin liên hệ sẽ được xóa bỏ. Bạn có chắc chắn xóa thông tin này");
				if (r == true) {
					var URL = $(this).attr("data-href");
					
					$.ajax({
						type: "POST",
						url: URL,
						cache: false,
						success: function(html){
							
							notify_s('Thông báo','Bạn đã xóa thành công');
							
						}
					})
					$(this).closest("tbody.category tr").fadeOut(function(){$(this).remove()});
				} 
				
			});
		})
	</script>
	<div id="dialog">
			<iframe id="myIframe" src="" width="100%" height="100%" style="border: 1px solid #ccc"></iframe>
	</div>
        	<script type="text/javascript">
			function closeModal() {
			    $("#dialog").dialog("close");
			}
			</script>