<?php if ($this->pageCount): ?>
<div class="paginationControl fo5 s14">
    <p align='center'>
	    <!--<div style="float:left">-->
      <!-- Previous page link -->
      <?php if (isset($this->previous)): ?>
     <a class="first red" href="<?php echo $this->url('sanpham',array('action'=>$action, 'id'=>@$id,'page'=>1)); ?>">&lt;&lt; Trang đầu&nbsp;&nbsp;</a>
     <a class="Previous red" href="<?php echo $this->url('sanpham',array('action'=>$action, 'id'=>@$id,'page'=>$this->previous)); ?>">&lt; Trang trước&nbsp;&nbsp;</a>      
      <?php else: ?>
      &lt;&lt; Trang đầu&nbsp;&nbsp;
      &lt; Trang trước&nbsp;&nbsp;
      <?php endif; ?>
      <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ($page != $this->current): ?>
        <a class="nopage red underline" href="<?php echo $this->url('sanpham',array('action'=>$action, 'id'=>@$id,'page'=>"$page")); ?>">
      <?php echo $page; ?>
      </a>&nbsp;
      <?php else: ?>
            <span class="nopage">
      <?php echo $page; ?>
    </span>
      </b>&nbsp;
      <?php endif; ?>
      <?php endforeach; ?>
      <?php if (isset($this->next)): ?>
      <a class="next red" href="<?php echo $this->url('sanpham',array('action'=>$action, 'id'=>@$id,'page'=>$this->next)); ?>">&nbsp;Trang tiếp theo &gt;</a>
      <a class="next red" href="<?php echo $this->url('sanpham',array('action'=>$action, 'id'=>@$id,'page'=>$this->pageCount)); ?>">&nbsp;Trang cuối &gt;&gt;</a>
      <?php else: ?>      	
	   &nbsp;Trang tiếp theo &gt;&nbsp;
	   &nbsp;Trang cuối &gt;&gt;&nbsp;
      <?php endif; ?>
    </p>
</div>
<?php endif; ?>